from flask import Flask, request, jsonify
from fuzzywuzzy import process
import json

# List of existing street names
street_names = [
    "11. aprila", 
	"15. februara", 
	"16. aprila", 
	"21. maja", 
	"23. srpske udarne divizije", 
	"23. srpske udarne divizije 1. prilaz", 
	"30. maja", 
	"4. Flavijeve legije", 
	"5. novembra", 
	"Batajnički bulevar", 
	"Bulevar Arsenija Čarnojevića", 
	"Narodnih heroja", 
	"Omladinskih brigada", 
	"Đakovačka", 
	"Đakona Avakuma", 
	"Đalinska", 
	"Đanga Rajnharta", 
	"Đačka", 
	"Đevđelijska", 
	"Đenovička", 
	"Đeravička", 
	"Đerdapska", 
	"Đoka Vojvodića", 
	"Đoka Kovačevića", 
	"Đoka Pavićevića", 
	"Đoke Bogdanovića", 
	"Đoke Krstića", 
	"Đorđa Jovanovića", 
	"Đorđa Andrejevića Kuna", 
	"Đorđa Vajferta", 
	"Đorđa Ilića", 
	"Đorđa Kode", 
	"Đorđa Kratovca", 
	"Đorđa Krstića", 
	"Đorđa Lobačeva", 
	"Đorđa Milovanovića", 
	"Đorđa Mihailovića", 
	"Đorđa Nestorovića", 
	"Đorđa Nešića", 
	"Đorđa Ognjanovića", 
	"Đorđa Pavlovića", 
	"Đorđa Pantelića", 
	"Đorđa Radaka", 
	"Đorđa Radojlovića", 
	"Đorđa Simića", 
	"Đorđa Stanojevića", 
	"Đorđa Stojkovića", 
	"Đorđa Tasića", 
	"Đorđa Čutukovića", 
	"Đorđa Šagića", 
	"Đuzepea Mancinija", 
	"Đuke Dinić", 
	"Đura Đapića", 
	"Đure Jakšića", 
	"Đure Gavele", 
	"Đure Gajića", 
	"Đure Daničića", 
	"Đure Kurepe", 
	"Đure Mađerčića", 
	"Đurićev prolaz", 
	"Đurićeva", 
	"Đurđa Balšića", 
	"Đurđa Boškovića Bate", 
	"Đurđevdanska", 
	"Đurđevića Tare", 
	"Đurđevke Čakarević", 
	"Đušina", 
	"Đuje i Dragoljuba", 
	"Jablanička", 
	"Jablanska", 
	"Jabuka", 
	"Jabučka", 
	"Javorska", 
	"Jagodinska", 
	"Jagoša Žarića", 
	"Jadranska", 
	"Jazačka", 
	"Jakova Galusa", 
	"Jakova Markovića", 
	"Jakova Hlipčijeva", 
	"Jakova Šarčevića", 
	"Jakšićeva", 
	"Jana Kolara", 
	"Janisa Janulisa", 
	"Janićija Živanovića", 
	"Janka Đurđevića", 
	"Janka Jankovića", 
	"Janka Brašića", 
	"Janka Veselinovića", 
	"Janka Katića", 
	"Janka Mišića", 
	"Janka Popovića", 
	"Janka Šafarika", 
	"Janković Stojana", 
	"Janče Jovanovića", 
	"Japanska", 
	"Jaroslava Čermaka", 
	"Jaroslava Černog", 
	"Jasenička", 
	"Jasenova", 
	"Jasenovačka", 
	"Jasenovačkih žrtava", 
	"Jasenovačkih mučenika", 
	"Jasenovog lista", 
	"Jasenska", 
	"Jasikova", 
	"Jasmina", 
	"Jasmine Jovanović", 
	"Jaspisa", 
	"Jastrebačka", 
	"Jastrebovljeva", 
	"Jatačka", 
	"Jatačka ulica", 
	"Jahorinska", 
	"Jaše Ignjatovića", 
	"Jaše Prodanovića", 
	"Janje Mihailovića", 
	"Jevrema Grujića", 
	"Jevrejska", 
	"Jevrejskih žrtava", 
	"Jedanaeste krajiške divizije", 
	"Jedrenska", 
	"Jezdićeva", 
	"Jezerska", 
	"Jezerska prolaz 1", 
	"Jezerska prolaz 2", 
	"Jezerska prolaz 3", 
	"Jezerska prolaz 4", 
	"Jezerska prolaz 5", 
	"Jezerska prolaz 6", 
	"Jelašnička", 
	"Jelezovačka", 
	"Jelene Ćetković", 
	"Jelene Anžujske", 
	"Jelene Balšić", 
	"Jelene Genčić", 
	"Jelene Kon", 
	"Jelene Lozanić", 
	"Jelene Mioč", 
	"Jelene Mrnjavčević", 
	"Jelene Radojkić", 
	"Jelene Šaulić Bojović", 
	"Jelenka Mihajlovića", 
	"Jelenov žleb", 
	"Jelisavete Andrejević", 
	"Jelisavete Dojkić", 
	"Jelisavete Načić", 
	"Jelička", 
	"Jelke Bojkić Makavejev", 
	"Jenkova", 
	"Jeremije Stanojevića", 
	"Jerneja Kopitara", 
	"Jerusalimska", 
	"Jesenjinova", 
	"Jefimijina", 
	"Jirečekova", 
	"Joakima Vujića", 
	"Joakima Rakovca", 
	"Jovana Đaje", 
	"Jovana Đorđevića", 
	"Jovana Janićijevića Burduša", 
	"Jovana Jankovića Lunge", 
	"Jovana Jovičevića", 
	"Jovana Joce Vujića", 
	"Jovana Ljubinkovića Pube", 
	"Jovana Ćirilova", 
	"Jovana Avakumovića", 
	"Jovana Andrejevića", 
	"Jovana Apostolovića", 
	"Jovana Belimarkovića", 
	"Jovana Belića", 
	"Jovana Berića", 
	"Jovana Bijelića", 
	"Jovana Boškovića", 
	"Jovana Brankovića", 
	"Jovana Brankovića 1. deo", 
	"Jovana Brankovića 2. deo", 
	"Jovana Brankovića 3. deo", 
	"Jovana Valente", 
	"Jovana Gajgera", 
	"Jovana Gligorijevića", 
	"Jovana Deretića", 
	"Jovana Dučića", 
	"Jovana Erdeljanovića", 
	"Jovana Žujovića", 
	"Jovana Ilkića", 
	"Jovana Isailovića", 
	"Jovana Karamate", 
	"Jovana Marinovića", 
	"Jovana Mikića", 
	"Jovana Milovanovića", 
	"Jovana Miodragovića", 
	"Jovana Muškatirovića", 
	"Jovana Naka", 
	"Jovana Nikolića Čokojića", 
	"Jovana Pačića", 
	"Jovana Popovića", 
	"Jovana Raškovića", 
	"Jovana Rajića", 
	"Jovana Ristića", 
	"Jovana Ružića", 
	"Jovana Sekulića", 
	"Jovana Stojsavljevića", 
	"Jovana Subotića", 
	"Jovana Todorovića", 
	"Jovana Tomića", 
	"Jovana Turomana", 
	"Jovana Tucakova", 
	"Jovana Uroša Nemanjića", 
	"Jovanička", 
	"Jovanke Jeftanović", 
	"Jovanke Bončić", 
	"Jovanke Radaković", 
	"Jove Despotovića", 
	"Jove Ilića", 
	"Jovice Vasiljevića", 
	"Jovijanova", 
	"Jože Plečnika", 
	"Joza Laurenčića", 
	"Joze Šćurle", 
	"Jozefa Jiričeka", 
	"Jonska", 
	"Jorgandžijska", 
	"Jorgovana", 
	"Jorja Tadića", 
	"Josipa Kolumba", 
	"Josipa Kulundžića", 
	"Josipa Novaka", 
	"Josipa Slavenskog", 
	"Josipa Telarevića", 
	"Josipa Šenera", 
	"Josifa Marinkovića", 
	"Josifa Tatića", 
	"Joce Jovanovića", 
	"Joce Živkovića", 
	"Jocina ada", 
	"Jošanička", 
	"Jojkićev Dunavac", 
	"Juvelirska", 
	"Jug Bogdanova", 
	"Juga Grizelja", 
	"Jugoslovenska", 
	"Južna", 
	"Južni bulevar", 
	"Južnomoravska", 
	"Južnomoravske brigade", 
	"Jula Brinera", 
	"Julije Vitgens", 
	"Junska", 
	"Jure Keroševića", 
	"Jurice Ribara", 
	"Jurija Gagarina", 
	"Jurija Rakitina", 
	"Justina Popovića", 
	"Juhorova", 
	"Juhorska", 
	"Ljevoška", 
	"Ljermontovljeva", 
	"Lješka", 
	"Ljiljane Žikić", 
	"Ljiljane Kontić", 
	"Ljiljane Krstić", 
	"Ljuba Vučkovića", 
	"Ljubana Jednaka", 
	"Ljube Jovanovića", 
	"Ljube Davidovića", 
	"Ljube Danilovića", 
	"Ljube Didića", 
	"Ljube Kovačevića", 
	"Ljube Moljca", 
	"Ljube Nedića", 
	"Ljube Tadića", 
	"Ljube Čupe", 
	"Ljube Šercera", 
	"Ljube Škiljevića", 
	"Ljubinke Bobić", 
	"Ljubice Đorđević", 
	"Ljubice Janković", 
	"Ljubice Di Sorno", 
	"Ljubice Ivošević-Dimitrov", 
	"Ljubice Ković", 
	"Ljubice Luković", 
	"Ljubice Ravasi", 
	"Ljubice Čakarević", 
	"Ljubičica", 
	"Ljubiše Jelenkovića", 
	"Ljubiše Jovanovića", 
	"Ljubiše Baje Bačića", 
	"Ljubiše Glišića", 
	"Ljubiše Miodragovića", 
	"Ljubinjska", 
	"Ljubićka", 
	"Ljubovijska", 
	"Ljubomira Đokovića", 
	"Ljubomira Jovanovića", 
	"Ljubomira Vukadinovića", 
	"Ljubomira Didića", 
	"Ljubomira Živkovića Španca", 
	"Ljubomira Ivanovića", 
	"Ljubomira Ivkovića Šuce", 
	"Ljubomira Petrovića", 
	"Ljubomira Stojanovića", 
	"Ljubostinjska", 
	"Ljubotenska", 
	"Ljubljanska", 
	"Ljudevita Štura", 
	"Ljutice Bogdana", 
	"Njegoševa", 
	"Ćehotinska", 
	"Ćilibara", 
	"Ćipikova", 
	"Ćira Daskalovića", 
	"Ćirila i Metodija", 
	"Ćukovačka", 
	"Ćukovački kut", 
	"Ćukovački rub", 
	"Ćupričin potok", 
	"Ćuprijska", 
	"Ćurtovo brdo", 
	"Ćurčijina", 
	"Ćustendilska", 
	"Džez sokače", 
	"Džesija Ovensa", 
	"Džona Kenedija", 
	"Džona Frontinghama", 
	"Džordža Vašingtona", 
	"Džordža Kenana", 
	"Džordža Orvela", 
	"Abebe Bikile", 
	"Aberdareva", 
	"Avalska", 
	"Avalskog venca", 
	"Avde Karabegovića", 
	"Avenija Beograd", 
	"Avijatičara", 
	"Avijatičarski put", 
	"Avijatičarski trg", 
	"Avrama Vinavera", 
	"Avrama Levića", 
	"Avrama Petronijevića", 
	"Agaruška", 
	"Agate Kristi", 
	"Ada Huja", 
	"Adama Bogosavljevića", 
	"Admirala Vukovića", 
	"Admirala Geprata", 
	"Admiralska", 
	"Aerodromska", 
	"Azanjska", 
	"Akademika Mihaila Markovića", 
	"Akademska", 
	"Akademski plato", 
	"Akira Kurosave", 
	"Akrobate Aleksića", 
	"Alana Tjuringa", 
	"Alaska", 
	"Albanske spomenice", 
	"Albera Kamija", 
	"Alberta Ajnštajna", 
	"Alberta Vajsa", 
	"Albrehta Direra", 
	"Aleksandra Đorđevića", 
	"Aleksandra Belića", 
	"Aleksandra Borodina", 
	"Aleksandra Bugarskog", 
	"Aleksandra Velikog", 
	"Aleksandra Vojinovića", 
	"Aleksandra Vuča", 
	"Aleksandra Gavrića", 
	"Aleksandra Glišića", 
	"Aleksandra Deroka", 
	"Aleksandra Dime", 
	"Aleksandra Dubčeka", 
	"Aleksandra Makedonskog", 
	"Aleksandra Nevskog", 
	"Aleksandra Pavlovića", 
	"Aleksandra Petrovića", 
	"Aleksandra Popovića", 
	"Aleksandra Sandića", 
	"Aleksandra Solženjicina", 
	"Aleksandra Stamboliskog", 
	"Aleksandra Stojanovića", 
	"Aleksandra Sunturlića", 
	"Aleksandra Tirnanića Tirketa", 
	"Aleksandra Tišme", 
	"Aleksandra Tijanića", 
	"Aleksandra Tomaševića", 
	"Aleksandra Fleminga", 
	"Aleksandrovačka", 
	"Alekse Bačvanskog", 
	"Alekse Dundića", 
	"Alekse Žujovića", 
	"Alekse Markišića", 
	"Alekse Nenadovića", 
	"Aleksinačka", 
	"Aleksinačkih rudara", 
	"Aleja mira", 
	"Alibunarska", 
	"Alimpija Vasiljevića", 
	"Alojza Šmausa", 
	"Alpskih ruža", 
	"Alfreda Nobela", 
	"Amadova", 
	"Amelije Erhart", 
	"Anastasa Jovanovića", 
	"Anastasije Spasić", 
	"Andre Đorđevića", 
	"Andre Jovića", 
	"Andre Nikolića", 
	"Andre Stevanovića", 
	"Andreja Andrejevića", 
	"Andreja Vitruka", 
	"Andreja Mitrovića", 
	"Andreja Tarkovskog", 
	"Andreje Damjanovića", 
	"Andreje Pregera", 
	"Andrije Vukovića", 
	"Andrije Habuša", 
	"Andrijevačka", 
	"Andrićev venac", 
	"Ane Ahmatove", 
	"Ane Bešlić", 
	"Ane Glinskaje Jakšić", 
	"Ane Dobeš", 
	"Ane Frank", 
	"Anete Andrejević", 
	"Anice Savić Rebac", 
	"Anke Matić", 
	"Anke Obrenović", 
	"Anke Stojilović", 
	"Anri Matisa", 
	"Anrija Žamea", 
	"Ante Abramovića", 
	"Ante Bogićevića", 
	"Ante Lambaše", 
	"Ante Mudrovčića", 
	"Antifašističke borbe", 
	"Antona Aškerca", 
	"Antona Klemenčića", 
	"Antona Čehova", 
	"Antonija Pantovića", 
	"Antonije Javornik", 
	"Apatinska", 
	"Apisova", 
	"Aradska", 
	"Aranđelovačka", 
	"Ariljačka", 
	"Ariljska", 
	"Arsena Dedića", 
	"Arhiepiskopa Danila", 
	"Arhimandrita Gerasima Zelića", 
	"Arhitekte Ilkića", 
	"Arčibalda Rajsa", 
	"Astana", 
	"Astronomska", 
	"Atanasija Nikolića", 
	"Atanasija Pulje", 
	"Atika", 
	"Atinska", 
	"Atlanska", 
	"Atlantska", 
	"Augusta Šenoe", 
	"Auto-voz", 
	"Autoput", 
	"Autoput za Zagreb", 
	"Autoput za Niš", 
	"Autoput za Novi Sad", 
	"Ahmeda Ademovića", 
	"Ace Joksimovića", 
	"Ace Simića", 
	"Ađutantska", 
	"Ajdanovačka", 
	"Ajzenštajnova", 
	"Aljehinova", 
	"Adžine livade", 
	"Baba-Višnjina", 
	"Bavarska", 
	"Bavarska ulica", 
	"Bagremova", 
	"Badema", 
	"Bakarska", 
	"Bakićeva", 
	"Balanička", 
	"Balzakova", 
	"Balkanska", 
	"Baltička", 
	"Balšina", 
	"Bana Ivaniša", 
	"Banatska", 
	"Banijska", 
	"Banovačka", 
	"Banovićka", 
	"Banstolska", 
	"Barajevska", 
	"Baranjska", 
	"Barutana", 
	"Bata Lakina", 
	"Batajnički vinogradi", 
	"Batajnički drum", 
	"Batajnički drum 1. deo", 
	"Batajnički drum 10. deo", 
	"Batajnički drum 11. deo", 
	"Batajnički drum 13. deo", 
	"Batajnički drum 14. deo", 
	"Batajnički drum 15. deo", 
	"Batajnički drum 16. deo", 
	"Batajnički drum 17. deo", 
	"Batajnički drum 2. deo", 
	"Batajnički drum 3. deo", 
	"Batajnički drum 4. deo", 
	"Batajnički drum 5. deo", 
	"Batajnički drum 6. deo", 
	"Batajnički drum 7. deo", 
	"Batajnički drum 8. deo", 
	"Batajnički drum 9. deo", 
	"Batajnički put", 
	"Batajničkih žrtava", 
	"Batinske bitke", 
	"Batočinska", 
	"Batutova", 
	"Bahtijara Vagabzade", 
	"Bačvanska", 
	"Bačvarska", 
	"Bačka", 
	"Bački ilovik", 
	"Baš-Čelika", 
	"Bašaidska", 
	"Baštovanska", 
	"Bajdina", 
	"Bajronova", 
	"Banjalučka", 
	"Banjica 2", 
	"Banjička", 
	"Banjički breg", 
	"Banjički potok", 
	"Banjički put", 
	"Banjičkih žrtava", 
	"Banjska", 
	"Bebelova", 
	"Begejska", 
	"Begonija", 
	"Bežanijska", 
	"Bežanijski zimovnik", 
	"Bežanijskih ilegalaca", 
	"Beže Albahari", 
	"Bezdanska", 
	"Bezistan", 
	"Bekerelova", 
	"Bekić salaš", 
	"Bela zemlja", 
	"Bela stena Vinogradi", 
	"Belarica 49. nova", 
	"Belarica 50. nova", 
	"Belarica 51. nova", 
	"Belarica 52. nova", 
	"Belarica 53. nova", 
	"Belarica 54. nova", 
	"Belarica 55. nova", 
	"Belarica 56. nova", 
	"Belarica 57. nova", 
	"Belarica 58. nova", 
	"Belarica 59. nova", 
	"Belarica 60. nova", 
	"Belarica 61. nova", 
	"Belarica 62. nova", 
	"Belarica 63. nova", 
	"Belarička", 
	"Belgijska", 
	"Belgrade viewpoint", 
	"Bele Rohel Frajnd", 
	"Bele breze", 
	"Bele vode", 
	"Belegiška", 
	"Belegiška 1. deo", 
	"Belegiška 2. deo", 
	"Belegiška 3. deo", 
	"Beli potok", 
	"Belimarkovićeva", 
	"Belih božura", 
	"Belih narcisa", 
	"Belih jasenova", 
	"Belička", 
	"Belo vrelo", 
	"Belobrdska", 
	"Belog bagrema", 
	"Belog duda", 
	"Belokrajinska", 
	"Belomorska", 
	"Belopalanačka", 
	"Belopoljska", 
	"Belotinačka", 
	"Belocrkvanska", 
	"Belućka", 
	"Belfortska", 
	"Benzonova", 
	"Beogradska", 
	"Beogradskog bataljona", 
	"Beodranska", 
	"Beranska", 
	"Beračka", 
	"Berlinskog kongresa", 
	"Bertranda Rasela", 
	"Besmrtnog bataljona", 
	"Bete Vukanović", 
	"Bečejska", 
	"Bečmenska", 
	"Bešanovačka", 
	"Beljanička", 
	"Bilećka", 
	"Biluška", 
	"Bilce", 
	"Biničkog", 
	"Birčaninova", 
	"Biserna", 
	"Bistrička", 
	"Bitke na Drini", 
	"Bitke na Neretvi", 
	"Bitoljska", 
	"Bihaćka", 
	"Biljane Jovanović", 
	"Blagajska", 
	"Blage Marije", 
	"Blagoja Jovovića", 
	"Blagoja Marjanovića Moše", 
	"Blagoja Parovića", 
	"Blagojevićev prolaz", 
	"Blaža Popivode", 
	"Blaznavčeva", 
	"Bledska", 
	"Bobana Milića", 
	"Bobana Tomovića", 
	"Bogdana Jugovića Hajnca", 
	"Bogdana Bogdanovića", 
	"Bogdana Bolte", 
	"Bogdana Velaševića", 
	"Bogdana Žerajića", 
	"Bogdana Kosanovića", 
	"Bogdana Kršića", 
	"Bogdana Nestorovića", 
	"Bogdana Popovića", 
	"Bogdana Tirnanića", 
	"Bogoboja Atanackovića", 
	"Bogovinska", 
	"Bogomira Aćimovića", 
	"Bogojavljenska", 
	"Bogoljuba Uroševića", 
	"Bogoljuba Čukića", 
	"Bogutovačka", 
	"Boemsko sokače", 
	"Bože Jankovića", 
	"Bože Jeremića", 
	"Bože Baucala", 
	"Bože Dreničkog", 
	"Bože Petrovića", 
	"Božidara Kneževića", 
	"Božidara Kovačevića", 
	"Božidara Pavićevića", 
	"Božidara Savićevića", 
	"Božidara Stanojevića", 
	"Božidara Timotijevića", 
	"Božidara Ferjančića", 
	"Božidarčeva", 
	"Božice Divnić", 
	"Božićna", 
	"Božurova", 
	"Bokeljska", 
	"Bore Vukmirovića", 
	"Bore Markovića", 
	"Bore Prodanovića", 
	"Bore Radojevića", 
	"Bore Stankovića", 
	"Bore Stankovića Makiš", 
	"Borivoja Bore Todorovića", 
	"Borivoja Vukova", 
	"Borivoja Drobnjakovića", 
	"Borivoja Kostića", 
	"Borivoja Milojevića", 
	"Borivoja Stevanovića", 
	"Borivoja Tasovca", 
	"Borisava Atanaskovića", 
	"Borisavljevićeva", 
	"Borislava Blagojevića", 
	"Borislava Pekića", 
	"Borova", 
	"Borozanova", 
	"Borska", 
	"Borhesova", 
	"Borčanska", 
	"Bosanska", 
	"Bosanske Krajine", 
	"Bose Milićević", 
	"Bose Ranković", 
	"Bose Cvetić", 
	"Bosiljke Janić", 
	"Bosiljke Boci", 
	"Bosiljke Matić", 
	"Bosutska", 
	"Bohinjska", 
	"Bohumila Hrabala", 
	"Boce i Jakše", 
	"Boška Buhe", 
	"Boška Desnice", 
	"Boška Petrovića", 
	"Boška Tokina", 
	"Bođanska", 
	"Bojana Đordumovića", 
	"Bojana Stupice", 
	"Bojana Stupice 1. deo", 
	"Bojadžinska", 
	"Bojnička", 
	"Bojčinska", 
	"Boljetinska", 
	"Brainska", 
	"Brane Ćosića", 
	"Brane Petrovića", 
	"Brane Petronijevića", 
	"Brane Crnčevića", 
	"Branivoja Jovanovića Brane", 
	"Branimira Ćosića", 
	"Branislava Barišića Doktora", 
	"Branislava Barišića Doktora 1. deo", 
	"Branislava Barišića Doktora 10. deo", 
	"Branislava Barišića Doktora 11. deo", 
	"Branislava Barišića Doktora 12. deo", 
	"Branislava Barišića Doktora 2. deo", 
	"Branislava Barišića Doktora 3. deo", 
	"Branislava Barišića Doktora 4. deo", 
	"Branislava Barišića Doktora 5. deo", 
	"Branislava Barišića Doktora 6. deo", 
	"Branislava Barišića Doktora 7. deo", 
	"Branislava Barišića Doktora 8. deo", 
	"Branislava Barišića Doktora 9. deo", 
	"Branislava Borozana", 
	"Branislava Paraća", 
	"Branislava Petronijevića", 
	"Branislava Stankovića", 
	"Braničevska", 
	"Branka Ćopića", 
	"Branka Bulata", 
	"Branka Gavele", 
	"Branka Živkovića", 
	"Branka Krsmanovića", 
	"Branka Krstića", 
	"Branka Miljkovića", 
	"Branka Miljuša", 
	"Branka Momirova", 
	"Branka Momirova ulica 1.", 
	"Branka Petkovića", 
	"Branka Pešića", 
	"Branka Plećaša", 
	"Branka Popovića", 
	"Branka Radičevića", 
	"Branka Cvetkovića", 
	"Branka Šotre", 
	"Branka Šljivića", 
	"Branke Đukić", 
	"Brankov most", 
	"Brankova", 
	"Bracana Bracanovića", 
	"Bračka", 
	"Braće Jelića", 
	"Braće Jeremića", 
	"Braće Jerković", 
	"Braće Jugovića", 
	"Braće Abafi", 
	"Braće Amar", 
	"Braće Barišića", 
	"Braće Baruh", 
	"Braće Bajagić", 
	"Braće Vojnovića", 
	"Braće Vučković", 
	"Braće Gavrilovića", 
	"Braće Grim", 
	"Braće Deroko", 
	"Braće Živojinović", 
	"Braće Kovač", 
	"Braće Krsmanović", 
	"Braće Krstić", 
	"Braće Krnješevac", 
	"Braće Lenard", 
	"Braće Limijer", 
	"Braće Lukića", 
	"Braće Marinković", 
	"Braće Matić", 
	"Braće Miladinov", 
	"Braće Milić", 
	"Braće Mitrovića", 
	"Braće Mihajlović Tripić", 
	"Braće Micić", 
	"Braće Nastasijević", 
	"Braće Nedića", 
	"Braće Neštinac", 
	"Braće Radišić", 
	"Braće Radovanovića", 
	"Braće Ribnikar", 
	"Braće Ristić", 
	"Braće Savića", 
	"Braće Smiljanića", 
	"Braće Smiljanića 1. deo", 
	"Braće Smiljanića 2. deo", 
	"Braće Smiljanića 3. deo", 
	"Braće Srnić", 
	"Braće Stošić", 
	"Braće Todorovića", 
	"Braće Fogl", 
	"Braće Škerović", 
	"Brdovita", 
	"Brdska", 
	"Bregalnička", 
	"Bregovita", 
	"Breza", 
	"Breze", 
	"Breskvin cvet", 
	"Brestova", 
	"Brestovačka", 
	"Brehtova", 
	"Brzakova", 
	"Brzećka", 
	"Brigadirska", 
	"Briletova", 
	"Briselska", 
	"Brodaraca", 
	"Brodarska", 
	"Brodska", 
	"Brsjačka", 
	"Bruska", 
	"Brđanska", 
	"Bubanjskih žrtava", 
	"Buda Tomovića", 
	"Budvanska", 
	"Budimira Davidovića", 
	"Budimska", 
	"Budmanijeva", 
	"Bukovička", 
	"Bukureška", 
	"Bukuljska", 
	"Bulevar JNA", 
	"Bulevar Arsenija Čarnojevića", 
	"Bulevar Vudroa Vilsona", 
	"Bulevar Zorana Đinđića", 
	"Bulevar Mihajla Pupina", 
	"Bulevar Nikole Tesle", 
	"Bulevar Peka Dapčevića", 
	"Bulevar Franše d'Eperea", 
	"Bulevar Crvene armije", 
	"Bulevar vojvode Bojovića", 
	"Bulevar vojvode Mišića", 
	"Bulevar vojvode Putnika", 
	"Bulevar despota Stefana", 
	"Bulevar kneza Aleksandra Karađorđevića", 
	"Bulevar kralja Aleksandra", 
	"Bulevar maršala Tolbuhina", 
	"Bulevar mladih", 
	"Bulevar oslobođenja", 
	"Bulevar patrijarha Pavla", 
	"Bulevar umetnosti", 
	"Bulevar heroja sa Košara", 
	"Bulevarska", 
	"Bulija Benciona", 
	"Burgerovih", 
	"Businjska bara 1. nova", 
	"Businjska bara 2. nova", 
	"Businjska bara 3. nova", 
	"Bujanovačka", 
	"Buljubašina voda", 
	"Bjelanovićeva", 
	"Bjelasička", 
	"Vazduhoplovnih eskadrila", 
	"Vaznesenjska", 
	"Valentina Vodnika", 
	"Valoge", 
	"Valtazara Bogišića", 
	"Valterova", 
	"Valtrovićeva", 
	"Van Goga", 
	"Vanđela Tome", 
	"Varaždinska", 
	"Varvarinska", 
	"Vardarska", 
	"Vardenička", 
	"Vareška", 
	"Varovnička", 
	"Vartina", 
	"Vartkesova", 
	"Vasa Ćukovića", 
	"Vasa Čubrilovića", 
	"Vase Lazarevića", 
	"Vase Pantelića", 
	"Vase Pelagića", 
	"Vase Stajića", 
	"Vase Čarapića", 
	"Vasilija Đurovića Vaka", 
	"Vasilija Đurovića Žarkog", 
	"Vasilija Vasilijevića", 
	"Vasilija Ivanovića", 
	"Vasilija Kandinskog", 
	"Vasilija Mokranjca", 
	"Vasilija Rankovića Baće", 
	"Vasilije Radojčić", 
	"Vaska Pope", 
	"Vasojevićka", 
	"Vatroslava Jagića", 
	"Vajara Đoke Jovanovića", 
	"Vajara Živojina Lukića", 
	"Vajarska", 
	"Vajfertova", 
	"Valjevska", 
	"Veziljska", 
	"Velbuška", 
	"Vele Nigrinove", 
	"Velebitska", 
	"Velemajstora Bore Kostića", 
	"Veletinska", 
	"Velibora Gligorića", 
	"Velizara Stankovića", 
	"Velike međe nova 14", 
	"Velike međe nova 15", 
	"Velike međe nova 16", 
	"Velike međe nova 17", 
	"Velike međe nova 18", 
	"Velike međe nova 19", 
	"Velike međe nova 20", 
	"Velike međe nova 21", 
	"Velike međe nova 22", 
	"Velike međe nova 23", 
	"Velike međe nova 24", 
	"Velike međe nova 25", 
	"Velike međe nova 26", 
	"Velike međe nova 27", 
	"Velike stepenice", 
	"Veliki Kalemegdan", 
	"Veliki trg", 
	"Veliko silazno stepenište", 
	"Veliko stepenište", 
	"Velikozabranska", 
	"Velikomoravska", 
	"Velimira Bate Živojinovića", 
	"Velimira Životića", 
	"Velimira Rajića", 
	"Velimira Teodorovića", 
	"Velimirovićev prolaz", 
	"Velisava Vulovića", 
	"Velislava Vulovića", 
	"Venac Milice Vučetić-Trepuše", 
	"Venizelosova", 
	"Venčačka", 
	"Vere Đukić", 
	"Vere Dedović", 
	"Vere Dimitrijević", 
	"Vere Miščević", 
	"Veselina Masleše", 
	"Veselina Čajkanovića", 
	"Veslarska", 
	"Vespučijeva", 
	"Veternička", 
	"Velje Miljkovića", 
	"Veljka Dugoševića", 
	"Veljka Lukića Kurjaka", 
	"Veljka Marinkovića", 
	"Veljka Milankovića", 
	"Veljka Milićevića", 
	"Veljka Petrovića", 
	"Veljka Radenovića", 
	"Veljka Ramadanovića", 
	"Veljka Stanojevića", 
	"Vidaka Markovića", 
	"Vidakovićeva", 
	"Vide Jocić", 
	"Vide Pavlović", 
	"Vidikovac", 
	"Vidikovačka", 
	"Vidikovački venac", 
	"Vidovdanska", 
	"Vidska", 
	"Vizantijska", 
	"Vikentija Rakića", 
	"Viktora Bubnja", 
	"Viktora Igoa", 
	"Viktora Novaka", 
	"Viktora Starčića", 
	"Vile Ravijojle", 
	"Vili Branta", 
	"Viline vode", 
	"Vilovskog", 
	"Vinarska", 
	"Vinka Arnerija", 
	"Vinka Grdana", 
	"Vinogradi", 
	"Vinogradska", 
	"Vinogradski venac", 
	"Vinodolska", 
	"Vinčanska", 
	"Vipavska", 
	"Virpazarska", 
	"Virdžinije Vulf", 
	"Visariona Pavlovića", 
	"Visoka", 
	"Visokog Stevana", 
	"Visočka", 
	"Vitanovačka", 
	"Viteza Pavla Orlovića", 
	"Vitezova Karađorđeve zvezde", 
	"Viteška", 
	"Vitinska", 
	"Vitomira Ljubičića", 
	"Vitrukova", 
	"Viševačka", 
	"Višegradska", 
	"Viška", 
	"Višnjička", 
	"Višnjički venac", 
	"Višnjićev pasaž", 
	"Višnjićeva", 
	"Vijetnamska", 
	"Vinjage", 
	"Vladana Desnice", 
	"Vladanova", 
	"Vlade Aksentijevića", 
	"Vlade Bjelića", 
	"Vlade Divljana", 
	"Vlade Ilića", 
	"Vlade Obradovića", 
	"Vladete Jerotića", 
	"Vladete Kovačevića", 
	"Vladete Popovića Pineckog", 
	"Vladetina", 
	"Vladike Danila", 
	"Vladike Nikolaja Velimirovića", 
	"Vladike Platona", 
	"Vladimira Jevtovića", 
	"Vladimira Jovanovića", 
	"Vladimira Joksića", 
	"Vladimira Ćetkovića", 
	"Vladimira Ćorovića", 
	"Vladimira Aleksića", 
	"Vladimira Bečića", 
	"Vladimira Vasića", 
	"Vladimira Vujovića", 
	"Vladimira Gaćinovića", 
	"Vladimira Gortana", 
	"Vladimira Dvornikovića", 
	"Vladimira Dujića", 
	"Vladimira Karića", 
	"Vladimira Matijevića", 
	"Vladimira Mitrovića", 
	"Vladimira Nazora", 
	"Vladimira Nikolića", 
	"Vladimira Perića", 
	"Vladimira Petkovića", 
	"Vladimira Pogačića", 
	"Vladimira Popovića", 
	"Vladimira Radovanovića", 
	"Vladimira Radoičića", 
	"Vladimira Rolovića", 
	"Vladimira Stojančevića", 
	"Vladimira Tomanovića", 
	"Vladimira Farmakovskog", 
	"Vladimira Čopića", 
	"Vladislava Bajčevića", 
	"Vladislava Kaćanskog", 
	"Vladislava Lalickog", 
	"Vladislava Petkovića Disa", 
	"Vlasenička", 
	"Vlasinska", 
	"Vlastimira Đuze Stojiljkovića", 
	"Vlastimira Gavrika", 
	"Vlastimira Lazarevića", 
	"Vlastimira Pavlovića Carevca", 
	"Vlaha Bukovca", 
	"Vlašićka", 
	"Vlaška", 
	"Vlajka Đuranovića", 
	"Vlajkovićeva", 
	"Vodeničarska", 
	"Vodice", 
	"Vodnička", 
	"Vodovodska", 
	"Vodovodska 2. deo", 
	"Vodovodska 6. deo", 
	"Vodovodska prilaz", 
	"Vožda Đorđa Stratimirovića", 
	"Volgina", 
	"Voronješka", 
	"Vojačka", 
	"Vojvode Đurovića", 
	"Vojvode Jakše", 
	"Vojvode Jovana Stojkovića", 
	"Vojvode Ante Čolaka", 
	"Vojvode Atanasija Čarapića", 
	"Vojvode Baćevića", 
	"Vojvode Blažete", 
	"Vojvode Bogdana", 
	"Vojvode Bojovića", 
	"Vojvode Brane", 
	"Vojvode Vasilija Trbića", 
	"Vojvode Vlahovića", 
	"Vojvode Vojislava Vojinovića", 
	"Vojvode Vratka", 
	"Vojvode Vuka", 
	"Vojvode Dobrnjca", 
	"Vojvode Dovezenskog", 
	"Vojvode Dojčina", 
	"Vojvode Dragomira", 
	"Vojvode Draška Popovića", 
	"Vojvode Katića", 
	"Vojvode Kačerskog", 
	"Vojvode Kujundžića", 
	"Vojvode Milenka", 
	"Vojvode Milovanovića", 
	"Vojvode Micka Krstića", 
	"Vojvode Miljana Vukova", 
	"Vojvode Nikole Stanjevića", 
	"Vojvode Novaka", 
	"Vojvode Novaka 1. deo", 
	"Vojvode Novaka 10. deo", 
	"Vojvode Novaka 11. deo", 
	"Vojvode Novaka 12. deo", 
	"Vojvode Novaka 13. deo", 
	"Vojvode Novaka 2. deo", 
	"Vojvode Novaka 3. deo", 
	"Vojvode Novaka 4. deo", 
	"Vojvode Novaka 5. deo", 
	"Vojvode Novaka 6. deo", 
	"Vojvode Novaka 7. deo", 
	"Vojvode Novaka 8. deo", 
	"Vojvode Novaka 9. deo", 
	"Vojvode Petka", 
	"Vojvode Petra Šekularca", 
	"Vojvode Plamenca", 
	"Vojvode Prijezde", 
	"Vojvode Radula", 
	"Vojvode Savatija", 
	"Vojvode Sime Popovića", 
	"Vojvode Skopljanca", 
	"Vojvode Stepe", 
	"Vojvode Stojkovića", 
	"Vojvode Tankosića", 
	"Vojvode Toze", 
	"Vojvode Čupića", 
	"Vojvode Šupljikca", 
	"Vojvodska", 
	"Vojvođanska", 
	"Vojvođanskih brigada", 
	"Voje Veljkovića", 
	"Voje Radića", 
	"Vojina Đurašinovića Kostje", 
	"Vojina Bakića", 
	"Vojina Dajovića", 
	"Vojislava Jovanovića Maramba", 
	"Vojislava Avakumovića", 
	"Vojislava Vokija Kostića", 
	"Vojislava Vučkovića", 
	"Vojislava Ilića", 
	"Vojislava Lubarde", 
	"Vojislava Mićovića", 
	"Vojislava Nanovića", 
	"Vojislava Radovanovića", 
	"Vojislava Rakonjca", 
	"Vojlovička", 
	"Vojna", 
	"Vojna pošta", 
	"Vojni put 1", 
	"Vojni put 1 - Vojni put 2", 
	"Vojni put 2", 
	"Vojnićka", 
	"Voćarska", 
	"Vranićka", 
	"Vranovačka", 
	"Vrapčebrdska", 
	"Vračarski srez", 
	"Vranjska", 
	"Vrbaska", 
	"Vrbnička", 
	"Vrbska", 
	"Vrdnička", 
	"Vrtlarska", 
	"Vrčinska", 
	"Vršačka", 
	"Vrnjačka", 
	"Vuka Bojovića", 
	"Vuka Vrčevića", 
	"Vuka Karadžića", 
	"Vuka Mandušića", 
	"Vuka Marinkovića", 
	"Vukasovićeva", 
	"Vukašina Antića", 
	"Vukašina Mandrape", 
	"Vukašina Mrnjavčevića", 
	"Vukice Mitrović", 
	"Vukova", 
	"Vukovarska", 
	"Vučevska", 
	"Vučedolska", 
	"Vučitrnska", 
	"Vučićev prolaz", 
	"Vujadina Boškova", 
	"Vujanska", 
	"Vjekoslava Afrića", 
	"Vjekoslava Kovača", 
	"Gavre Plavšića", 
	"Gavrila Popovića", 
	"Gavrila Principa", 
	"Gavrila Rodića", 
	"Gazimestanska", 
	"Galerija ulica", 
	"Galilejeva", 
	"Galipoljska", 
	"Gamzigradska", 
	"Gaminska", 
	"Gandijeva", 
	"Gardijska", 
	"Gardoška", 
	"Garibaldijeva", 
	"Garsije Lorke", 
	"Gastona Gravijea", 
	"Gatačka", 
	"Gaudijeva", 
	"Gajeva", 
	"Gajićev sokak", 
	"Gajski put", 
	"Gvozdenog puka", 
	"Gvozdićeva", 
	"Gedeona Dunđerskog", 
	"Generala Đoke Popovića", 
	"Generala Ljubomira Milića", 
	"Generala Anrija", 
	"Generala Aračića", 
	"Generala Božidara Jankovića", 
	"Generala Vasića", 
	"Generala Vladimira Kondića", 
	"Generala Vrangela", 
	"Generala Ždanova", 
	"Generala Živka Pavlovića", 
	"Generala Zaha", 
	"Generala Zgonjanina", 
	"Generala Lešjanina", 
	"Generala Milutina Vlajića", 
	"Generala Mihajla Živkovića", 
	"Generala Mihajla Nedeljkovića", 
	"Generala Nikodija Stefanovića", 
	"Generala Pavla Jurišića Šturma", 
	"Generala Petrovića", 
	"Generala Rašića", 
	"Generala Rajevskog", 
	"Generala Save Grujića", 
	"Generala Horvatovića", 
	"Generala Černjajeva", 
	"Generala Štefanika", 
	"Generala Šturma", 
	"Generalska", 
	"Georgija Mihailovića", 
	"Georgija Ostrogorskog", 
	"Geršićeva", 
	"Geteova", 
	"Gece Kona", 
	"Gizele Vuković", 
	"Gite Predić Nušić", 
	"Glavna", 
	"Glavna ulica", 
	"Glamočka", 
	"Glasinačka", 
	"Gledićka", 
	"Gligorija Jeftanovića", 
	"Gligorija Jovanovića", 
	"Gligorija Vozarevića", 
	"Glinkina", 
	"Glinska", 
	"Glinskih žrtava 1941. godine", 
	"Goveđi brod", 
	"Godominska", 
	"Goleška", 
	"Goli breg", 
	"Golijska", 
	"Golsvordijeva", 
	"Golubarska", 
	"Golubačka", 
	"Golubinačka", 
	"Gorana Gajića", 
	"Gorana Kovačića", 
	"Gordane Kosanović", 
	"Gorenjska", 
	"Gorička", 
	"Gorničevska", 
	"Gorska", 
	"Gorskog javora", 
	"Gornja", 
	"Gornjačka", 
	"Gornji vinogradi", 
	"Gornjogradska", 
	"Gornjomilanovačka", 
	"Gospodar Jevremova", 
	"Gospodar Jovanova", 
	"Gospodara Vučića", 
	"Gospodska", 
	"Gospođe Tasti", 
	"Gostivarska", 
	"Gočka", 
	"Gojka Nikoliša", 
	"Gojka Stipića", 
	"Grabovska", 
	"Gradačka", 
	"Gradašnička", 
	"Gradine", 
	"Graditeljska", 
	"Gradištanska", 
	"Gradište", 
	"Gradska ulica", 
	"Gradski park", 
	"Grambergova", 
	"Gramšijeva", 
	"Graničarska", 
	"Grahovska", 
	"Gračanička", 
	"Grbaljska", 
	"Grge Jankesa", 
	"Grge Andrijanovića", 
	"Grge Andrijanovića ulica 1.", 
	"Grge Andrijanovića ulica 2.", 
	"Grge Andrijanovića ulica 3.", 
	"Grge Andrijanovića ulica 4.", 
	"Grge Andrijanovića ulica 5.", 
	"Grge Andrijanovića ulica 6.", 
	"Grge Andrijanovića ulica 7.", 
	"Grgura Ninskog", 
	"Grgurevačka", 
	"Grdelička", 
	"Gregorčićeva", 
	"Grivštanska", 
	"Grivštanska ulica", 
	"Grigora Viteza", 
	"Grigorija Božovića", 
	"Grigorija Ivanoviča Samojlova", 
	"Grmeč 1. nova", 
	"Grmečka", 
	"Grnčarska", 
	"Grobljanska", 
	"Gročanska", 
	"Gročanske nahije", 
	"Gružanska", 
	"Gruzijska", 
	"Gruje Kočijaša", 
	"Gruje Miškovića", 
	"Grčića Milenka", 
	"Grčka", 
	"Gundulićev venac", 
	"Gundulićeva", 
	"Gusinjska", 
	"Guslara Peruna", 
	"Guslarska", 
	"Gustava Klimta", 
	"Gučevska", 
	"Gunjak", 
	"Gnjilanska", 
	"Davida Pajića", 
	"Davidovićeva", 
	"Davora Dujmovića", 
	"Davorina Jenka", 
	"Dalmatinska", 
	"Dalmatinske zagore", 
	"Dalmatinskih brigada", 
	"Danila Bate Stojkovića", 
	"Danila Bojovića", 
	"Danila Vladisavljevića", 
	"Danila Ilića", 
	"Danila Kiša", 
	"Danila Lekića Španca", 
	"Danila Medakovića", 
	"Danila Nikolića", 
	"Danila Srdića", 
	"Danilova", 
	"Danice Jovanović", 
	"Danice Antić", 
	"Danice Kojić", 
	"Danice Marković", 
	"Daničareva", 
	"Danijelova", 
	"Danka Popovića", 
	"Danonova", 
	"Danteova", 
	"Darvinova", 
	"Darinke Jevrić", 
	"Darinke Borović", 
	"Darinke Radović", 
	"Darosavačka", 
	"Daruvarska", 
	"Darje Koropkine", 
	"Daljska", 
	"Dva bela goluba", 
	"Dvadeset devetog novembra", 
	"Dvadeset drugog oktobra", 
	"Dvadeset prve divizije", 
	"Dvadeset sedmog marta", 
	"Dvadesetog aprila", 
	"Dvadesetog oktobra", 
	"Dvadesetosmog juna", 
	"Debarska", 
	"Debina", 
	"Devaldovih", 
	"Devetnaestog aprila", 
	"Devojačka", 
	"Degurička", 
	"Dedinjska", 
	"Deževska", 
	"Deli Jovanova", 
	"Deli Radivoja", 
	"Deliblatska", 
	"Deligradska", 
	"Delijska", 
	"Delnička", 
	"Delovi", 
	"Delfe Ivanjić", 
	"Denisa Ričija", 
	"Dervanova", 
	"Desanke Dugalić", 
	"Desanke Maksimović", 
	"Dese Ležajić", 
	"Deset avijatičara", 
	"Desetarska", 
	"Desetog kilometra", 
	"Desimira Stojkovića", 
	"Deskaševa", 
	"Desna obala Dunava", 
	"Despota Đurđa", 
	"Despota Ivaniša", 
	"Despota Olivera", 
	"Despota Uglješe", 
	"Despotovačka", 
	"Decembarska", 
	"Dečanska", 
	"Dečka", 
	"Dečja", 
	"Dejana Dubajića", 
	"Dejana Medakovića", 
	"Dejana Nastića", 
	"Dejana Spasovskog", 
	"Diane Budisavljević", 
	"Divne Đoković", 
	"Divne Đurić-Zamolo", 
	"Divčibarska", 
	"Divlje kruške", 
	"Divljih kestena", 
	"Divljih jabuka", 
	"Dimitrija Jovčića", 
	"Dimitrija Avramovića", 
	"Dimitrija Bačevića", 
	"Dimitrija Blagojevića", 
	"Dimitrija Vučenova", 
	"Dimitrija Georgijevića Starika", 
	"Dimitrija Gerasimovića", 
	"Dimitrija Davidovića", 
	"Dimitrija Danića", 
	"Dimitrija Isailovića", 
	"Dimitrija Katića", 
	"Dimitrija Kolarovića", 
	"Dimitrija Koturovića", 
	"Dimitrija Konjovića", 
	"Dimitrija Lazarova Raše", 
	"Dimitrija Marinkovića", 
	"Dimitrija Nešića", 
	"Dimitrija Nikolajevića", 
	"Dimitrija Paramendića", 
	"Dimitrija Parlića", 
	"Dimitrija Popovića", 
	"Dimitrija Puljevića", 
	"Dimitrija Sabova", 
	"Dimitrija Savića", 
	"Dimitrija Stamenkovića", 
	"Dimitrija Tucovića", 
	"Dimitrija Cincar Markovića", 
	"Dinarska", 
	"Dinka Tucakovića", 
	"Diplomatska kolonija", 
	"Diskont PKB nova 21.", 
	"Diskont PKB nova 22.", 
	"Disova", 
	"Dijega Rivere", 
	"Diljska", 
	"Dobanovačka", 
	"Dobanovački put", 
	"Dobanovački put - Vojni put jedan", 
	"Dobanovački put 1. deo", 
	"Dobanovački put 2. deo", 
	"Dobanovački put 3. deo", 
	"Dobanovački put 4. deo", 
	"Dobojska", 
	"Dobračina", 
	"Dobre Mitrovića", 
	"Dobrivoja Isailovića", 
	"Dobrivoja Petkovića", 
	"Dobrinovićeva", 
	"Dobrice Ćosića", 
	"Dobrice Milutinovića", 
	"Dobrice Novakovića", 
	"Dobrinjska", 
	"Dobrovoljačka", 
	"Dobrovoljnih vatrogasaca", 
	"Dobrodolska", 
	"Dobropoljska", 
	"Dobropoljski prolaz", 
	"Dodolska", 
	"Doktora Andrejke", 
	"Doktora Aćima Medovića", 
	"Doktora Bože Marinkovića", 
	"Doktora Vojislava Stojanovića", 
	"Doktora Dragoljuba Sretenovića", 
	"Doktora Koste Todorovića", 
	"Doktora Mila Boškovića", 
	"Doktora Milivoja Petrovića", 
	"Doktora Miloša Pantića", 
	"Doktora Milutina Zečevića", 
	"Doktora Nedeljka Ercegovca", 
	"Doktora Nenada Parente", 
	"Doktora Selimira Đorđevića", 
	"Doktora Čajkanovića", 
	"Doktorke Vere Popović", 
	"Doktorke Draginje Babić", 
	"Doktorke Izabele Haton", 
	"Doktorke Nade Petrović", 
	"Dol", 
	"Dolačka", 
	"Dolenjska", 
	"Dolinska", 
	"Dolovska", 
	"Domentijana Hilandarca", 
	"Domentijanova", 
	"Donska", 
	"Doris Lesing", 
	"Dositeja Novakovića", 
	"Dositejeva", 
	"Dostojevskog", 
	"Dojranska", 
	"Donja", 
	"Dr Đorđa Joanovića", 
	"Dr Jovana Danića", 
	"Dr Agostina Neta", 
	"Dr Aleksandra Kostića", 
	"Dr Aleksandra Radosavljevića", 
	"Dr Borislava Vujadinovića", 
	"Dr Velizara Kosanovića", 
	"Dr Velimirovića", 
	"Dr Vilijama Hantera", 
	"Dr Vladana Đorđevića", 
	"Dr Vojislava Stojanovića", 
	"Dr Drage Ljočić", 
	"Dr Dragiše Mišovića", 
	"Dr Dragoslava Popovića", 
	"Dr Dragutina Boškovića", 
	"Dr Žorža Matea", 
	"Dr Zore Ilić-Obradović", 
	"Dr Ivana Ribara", 
	"Dr Ive Popovića Đanija", 
	"Dr Kosanovića", 
	"Dr Koste Todorovića", 
	"Dr Lazara Genčića", 
	"Dr Ludviga Hiršvelda", 
	"Dr Milivoja Babića", 
	"Dr Miloša Radojčića", 
	"Dr Milutina Ivkovića", 
	"Dr Nedeljka Ercegovca", 
	"Dr Nika Miljanića", 
	"Dr Petra Markovića", 
	"Dr Radivoja Vukadinovića", 
	"Dr Riharda Burijana", 
	"Dr Save Popovića", 
	"Dr Stanoja Stefanovića", 
	"Dr Subotića starijeg", 
	"Dr Teodora Borockog", 
	"Dr Huga Klajna", 
	"Dr Čedomira Đurđevića", 
	"Dravska", 
	"Dragana Jeftića", 
	"Dragana Zarića", 
	"Dragana Lakovića", 
	"Dragana Lukića", 
	"Dragana Maksimovića", 
	"Dragana Mancea", 
	"Dragana Mauzera", 
	"Dragana Nikitovića", 
	"Dragana Rakića", 
	"Dragana Rodića", 
	"Dragana Sakana", 
	"Dragana Stojnića", 
	"Dragana Tankosića", 
	"Dragačevska", 
	"Dragačevskih trubača", 
	"Drage Gavrilović", 
	"Drage Dejanović", 
	"Drage Mihajlovića", 
	"Drage Spasić", 
	"Dragice Končar", 
	"Dragiše Brašovana", 
	"Dragiše Vasića", 
	"Dragiše Lapčevića", 
	"Dragiše Stanisavljevića", 
	"Dragiše Stojadinovića", 
	"Draginje Adamović", 
	"Draginje Gavrilović", 
	"Draginje Petrović", 
	"Draginje Radovanović", 
	"Draginjska", 
	"Draginjska ulica", 
	"Dragomira Arambašića", 
	"Dragomira Bojanića Gidre", 
	"Dragomira Brajkovića", 
	"Dragomira Felbe", 
	"Dragoslava Đorđevića Goše", 
	"Dragoslava Jovanovića", 
	"Dragoslava Petrovića", 
	"Dragoslava Srejovića", 
	"Dragoša Kalajića", 
	"Dragojla Dudića", 
	"Dragoljuba Jeličića", 
	"Dragoljuba Aleksića", 
	"Dragoljuba Milenkovića Bape", 
	"Dragoljuba Ristića", 
	"Dragutina Đorđevića", 
	"Dragutina Aleksića", 
	"Dragutina Anastasijevića", 
	"Dragutina Ilića", 
	"Dragutina Maslaća", 
	"Dragutina Medenjaka", 
	"Dragutina Milutinovića", 
	"Dragutina Mojovića", 
	"Dragutina Popovića", 
	"Dragutina Tomaševića", 
	"Draže Pavlovića", 
	"Dračka", 
	"Drvarska", 
	"Drvarske česme", 
	"Drežnička", 
	"Drenička", 
	"Drenova", 
	"Drenovačka", 
	"Drenovska", 
	"Držićeva", 
	"Drinićka", 
	"Drinska", 
	"Drinčićeva", 
	"Druge srpske armije", 
	"Drugovačka", 
	"Drugog septembra", 
	"Duboka bara", 
	"Duboka bara nova 1", 
	"Duboka bara nova jedan", 
	"Duborezačka", 
	"Dubočka", 
	"Dubrovačka", 
	"Dubljanska", 
	"Duvanjska", 
	"Dukatska", 
	"Dukljaninova", 
	"Duleta Jovanovića", 
	"Dunavska", 
	"Dunavski breg", 
	"Dunavski kej", 
	"Dunavskih alasa", 
	"Dunavskih virova", 
	"Dunđerska", 
	"Durkovića Jakšića", 
	"Durmitorska", 
	"Dušana Jakšića", 
	"Dušana Janićijevića", 
	"Dušana Jovanovića", 
	"Dušana Džamonje", 
	"Dušana Baranina", 
	"Dušana Brankovića", 
	"Dušana Vasiljeva", 
	"Dušana Veličkovića", 
	"Dušana Vlajića", 
	"Dušana Vukasovića", 
	"Dušana Vujisića", 
	"Dušana Dude Timotijevića", 
	"Dušana Živanovića", 
	"Dušana Kanazira", 
	"Dušana Kvedera", 
	"Dušana Krstića", 
	"Dušana Markovića Čipija", 
	"Dušana Matića", 
	"Dušana Mađarčića Korčagina", 
	"Dušana Mađarčića Korčagina 1. deo", 
	"Dušana Mađarčića Korčagina 2. deo", 
	"Dušana Miloševića", 
	"Dušana Popovića", 
	"Dušana Prelevića", 
	"Dušana Purića", 
	"Dušana Puđe", 
	"Dušana Radenkovića", 
	"Dušana Radovića", 
	"Dušana Srezojevića", 
	"Dušanovačka", 
	"Dušice Spasić", 
	"Duška Popova", 
	"Duška Trifunovića", 
	"Dunjačka", 
	"Evgenija Dumče", 
	"Eve Haljecke", 
	"Evelin Haverfild", 
	"Evropska", 
	"Egejska", 
	"Egipatska", 
	"Edvarda Griga", 
	"Edvarda Munka", 
	"Eduarda Mihela", 
	"Elvirina", 
	"Elvisa Prislija", 
	"Elija Fincija", 
	"Else Ignis", 
	"Emanuela Laskera", 
	"Emanuila Jankovića", 
	"Emila Zatopeka", 
	"Emila Zole", 
	"Emilijana Josimovića", 
	"Emilije Jakšić", 
	"Emira Dragulja", 
	"Endija Vorhola", 
	"Enrika Josifa", 
	"Enrika Paćija", 
	"Episkopa Nikolaja", 
	"Episkopa Sergeja", 
	"Esad-pašina", 
	"Eugena Vebera", 
	"Eugena Savojskog", 
	"Eufemije Jović", 
	"Žabljačka", 
	"Žagubička", 
	"Žada", 
	"Žana Sibelijusa", 
	"Žanke Stokić", 
	"Žarka Jovanovića", 
	"Žarka Bokuna", 
	"Žarka Vasiljevića", 
	"Žarka Vukovića Pucara", 
	"Žarka Miladinovića", 
	"Žarka Obreškog", 
	"Žarka Obreškog 1. deo", 
	"Žarka Obreškog 2. deo", 
	"Žarka Savića", 
	"Žarka Trpkovića", 
	"Žarkovačka", 
	"Žarkovački breg", 
	"Ždralova", 
	"Železnik", 
	"Železnička", 
	"Železnička kolonija Batajnica", 
	"Železnička stražara Zemun", 
	"Željka Bijelića", 
	"Željka Milivojevića", 
	"Željka Mihajlovića", 
	"Željka Tonšića", 
	"Željka Šijana", 
	"Živana Panića", 
	"Živana Saramandića", 
	"Živka Jovanovića", 
	"Živka Davidovića", 
	"Živka Karabiberovića", 
	"Živka Nastića Babe", 
	"Živka Petrovića", 
	"Živke Matić", 
	"Živorada Đukića", 
	"Živorada Grbića", 
	"Živorada Žike Mitrovića", 
	"Živorada Nastasijevića", 
	"Živorada Pavlovića", 
	"Živote Marinkovića", 
	"Živote Stepanovića", 
	"Živojina Ćuluma", 
	"Živojina Živojinovića", 
	"Živojina Žujovića", 
	"Živojina Lazića", 
	"Židovarska", 
	"Žike Markovića", 
	"Žike Mesarovića", 
	"Žike Pavlovića", 
	"Žike Stojkovića", 
	"Žikina", 
	"Žikice Jovanovića", 
	"Žikice Jovanovića Španca", 
	"Žirova", 
	"Žitna", 
	"Žitomislićka", 
	"Žička", 
	"Žorža Klemansoa", 
	"Žrnovska", 
	"Žrtava bombardovanja", 
	"Župa", 
	"Župana Vlastimira", 
	"Župana Pribila", 
	"Župana Časlava", 
	"Žute bukve", 
	"Zabran nova 1.", 
	"Zabran nova 10.", 
	"Zabran nova 11.", 
	"Zabran nova 2.", 
	"Zabran nova 3.", 
	"Zabran nova 4.", 
	"Zabran nova 5.", 
	"Zabran nova 6.", 
	"Zabran nova 7.", 
	"Zabran nova 8.", 
	"Zabran nova 9.", 
	"Zabranska", 
	"Zabrđanska", 
	"Zaviše Crnog", 
	"Zavodska", 
	"Zage Malivuk", 
	"Zage Malivuk ulica 1.", 
	"Zage Malivuk ulica 2.", 
	"Zage Malivuk ulica 3.", 
	"Zage Malivuk ulica 4.", 
	"Zagorke Berović", 
	"Zagrađe", 
	"Zadrugarska", 
	"Zadužbinska", 
	"Zapadno selište", 
	"Zapadnomoravska", 
	"Zapis", 
	"Zaplanjska", 
	"Zarija Vujoševića", 
	"Zarije Vujoševića", 
	"Zastavnička", 
	"Zahumska", 
	"Zaječarska", 
	"Zajcova", 
	"Zvezdarska", 
	"Zvezdarskih jelki", 
	"Zvečanska", 
	"Zvonka Marića", 
	"Zvonka Milenkovića", 
	"Zvornička", 
	"Zdravka Jovanovića", 
	"Zdravka Velimirovića", 
	"Zdravka Zupana", 
	"Zdravka Čelara", 
	"Zeke Buljubaše", 
	"Zelengorska", 
	"Zeleni venac", 
	"Zeleno brdo", 
	"Zelenjak", 
	"Zemunska", 
	"Zemunski put", 
	"Zemljoradnička", 
	"Zenička", 
	"Zetska", 
	"Zidarska", 
	"Zimonjićeva", 
	"Zire Adamovića", 
	"Zlatana Vaude", 
	"Zlatanovićev sokak", 
	"Zlatarićeva", 
	"Zlatarska", 
	"Zlate Petković", 
	"Zlatiborska", 
	"Zlatka Šnajdera", 
	"Zlotska", 
	"Zmaj Jovina", 
	"Zmaj Ognjena Vuka", 
	"Zmaja Ognjenog Vuka", 
	"Zmaja od Avale", 
	"Zmaja od Noćaja", 
	"Zmajeva", 
	"Zmajevac", 
	"Zmajevačka", 
	"Zmajevačka 2. red", 
	"Zografska", 
	"Zorana Jankovića", 
	"Zorana Bogavca", 
	"Zorana Gluščevića", 
	"Zorana Gostovića", 
	"Zorana Žunkovića", 
	"Zorana Mišića", 
	"Zorana Radmilovića", 
	"Zore Drempetić", 
	"Zore Petrović", 
	"Zorina", 
	"Zorice Božović", 
	"Zorke Manojlović", 
	"Zorke Todosić", 
	"Zrenjaninski put", 
	"Zrmanjska", 
	"Zuke Džumhura", 
	"Ibarska", 
	"Ibarski put", 
	"Ibrahima Babovića", 
	"Iva Senkovića", 
	"Ivan-begova", 
	"Ivana Đaje", 
	"Ivana Aksakova", 
	"Ivana Antića", 
	"Ivana Belića", 
	"Ivana Božića", 
	"Ivana V. Lalića", 
	"Ivana Gorana Kovačića", 
	"Ivana Gradnika", 
	"Ivana Gubijana", 
	"Ivana Delnegra Engleza", 
	"Ivana Kapistrana", 
	"Ivana Kneževića", 
	"Ivana Markovića Irca", 
	"Ivana Mičurina", 
	"Ivana Radovića", 
	"Ivana Sarića", 
	"Ivana Senkovića", 
	"Ivana Stojanovića", 
	"Ivangradska", 
	"Ivanke Muačević", 
	"Ivankovačka", 
	"Ivankovačke bitke", 
	"Ivanjička", 
	"Ive Vojnovića", 
	"Ive Marinkovića", 
	"Ivice Devčića", 
	"Ivićeva", 
	"Igmanska", 
	"Igora Vasiljeva", 
	"Ignjata Joba", 
	"Ignjata Bajlonija", 
	"Ignjata Stanimirovića", 
	"Idvorska", 
	"Ide Branovački", 
	"Idrijska", 
	"Izbička", 
	"Izviđačka", 
	"Izvorac", 
	"Izvorska", 
	"Izletnička", 
	"Izletnički put", 
	"Ikarbus 2. nova", 
	"Ikarbus 3. nova", 
	"Ikarbus 4. nova", 
	"Ilindenska", 
	"Ilirska", 
	"Iličićeva", 
	"Ilije Đuričića", 
	"Ilije Bosilja", 
	"Ilije Garašanina", 
	"Ilije Gojkovića", 
	"Ilije Guteše", 
	"Ilije Kolarevića", 
	"Ilije Kolovića", 
	"Ilije Pavlovića", 
	"Ilije Petrovića", 
	"Ilije Pop Tone Ilića", 
	"Ilije Praizovića", 
	"Ilije Radojevića", 
	"Ilije Rogulića", 
	"Ilije Stojadinovića", 
	"Ilije Stojanovića", 
	"Ilije Čalića", 
	"Indire Gandi", 
	"Inženjera Atanackovića", 
	"Inženjera Kapusa", 
	"Internacionalnih brigada", 
	"Inđijska", 
	"Irisa", 
	"Iriška", 
	"Irske desete divizije", 
	"Isaka Njutna", 
	"Isaka Singera", 
	"Isidora Bajića", 
	"Isidora Dobrovića", 
	"Isidora Stojanovića", 
	"Isidore Sekulić", 
	"Islama Grčkog", 
	"Ismeta Mujezinovića", 
	"Istarska", 
	"Istinićka", 
	"Istočno selište", 
	"Italijanska", 
	"Italijanskih partizana", 
	"Ite Rine", 
	"Ičkova", 
	"Ištvana Lakija", 
	"Iđoška", 
	"Kablarska", 
	"Kavadarska", 
	"Kadifa", 
	"Kadinjača", 
	"Kazandžijska", 
	"Kazimira Maljevića", 
	"Kakanjska", 
	"Kalvarice", 
	"Kalenićeva", 
	"Kalinovačka", 
	"Kalnička", 
	"Kalovita", 
	"Kaluđera Grigorija", 
	"Kamenac", 
	"Kamenička", 
	"Kamenogorska", 
	"Kamenorezačka", 
	"Kamijeva", 
	"Kamčatska", 
	"Kanadska", 
	"Kanarevo brdo", 
	"Kapablankina", 
	"Kapetan Mišina", 
	"Kapetana Džona Piplfoksa", 
	"Kapetana Branka Životića", 
	"Kapetana Zavišića", 
	"Kapetana Miloša Žunjića", 
	"Kapetana Miodraga Miletića", 
	"Kapetana Popovića", 
	"Kapetana Radiča Petrovića", 
	"Kapetanovićeva", 
	"Kaplara Babića", 
	"Kaplara Markovića", 
	"Kaplara Momčila Gavrića", 
	"Kaplarska", 
	"Karamatina", 
	"Karamutska", 
	"Karađorđev trg", 
	"Karađorđeva", 
	"Karla Belonija", 
	"Karla Lukača", 
	"Karla Soprona", 
	"Karlovačka", 
	"Karlovčićka", 
	"Karnegijeva", 
	"Karpatska", 
	"Karpoševa", 
	"Katanićeva", 
	"Katarine Jovanović", 
	"Katarine Ambrozić", 
	"Katarine Bogdanović", 
	"Katarine Ivanović", 
	"Katarine Milovuk", 
	"Katarine Popović Midžine", 
	"Katarine Holecev", 
	"Katice Opačić", 
	"Katićev Skver", 
	"Katićeva", 
	"Kačanička", 
	"Kačerska", 
	"Kačićeva", 
	"Kašikovićeva", 
	"Kađenička", 
	"Kajmakčalanska", 
	"Kajuhova", 
	"Kaljavi potok", 
	"Kaćanskog", 
	"Kvarnerska", 
	"Kedrova", 
	"Keisuke Oba", 
	"Keltska", 
	"Keplerova", 
	"Kesara Vojihne", 
	"Kesara Novaka", 
	"Kesara Preljuba", 
	"Kesara Hrelje", 
	"Kestenova", 
	"Kestenovog lista", 
	"Ketrin Makfejl", 
	"Kefalonijska", 
	"Kej na Adi Huji", 
	"Kej oslobođenja", 
	"Kiparska", 
	"Kirila Kutlika", 
	"Kirila Savića", 
	"Kirovljeva", 
	"Kisela voda", 
	"Kičevska", 
	"Kijevska", 
	"Kijevski potok", 
	"Kladovska", 
	"Klanička stara", 
	"Klanički kej", 
	"Klaonička", 
	"Klare Cetkin", 
	"Klenačka", 
	"Klin nova 12.", 
	"Klin nova 13.", 
	"Klinska", 
	"Klisina nova 10.", 
	"Klisina nova 8.", 
	"Klisina nova 9.", 
	"Kmeta Todorovića", 
	"Kneginje Julije", 
	"Kneginje Ljubice", 
	"Kneginje Anastasije", 
	"Kneginje Zorke", 
	"Kneževačka", 
	"Knežpoljska", 
	"Knez Miletina", 
	"Kneza Bogosava", 
	"Kneza Višeslava", 
	"Kneza Vlastimira", 
	"Kneza Danila", 
	"Kneza Žike Mihajlovića", 
	"Kneza Ive od Semberije", 
	"Kneza Miloša", 
	"Kneza Mihaila", 
	"Kneza Mutimira", 
	"Kneza Pavla Karađorđevića", 
	"Kneza Paskača", 
	"Kneza Petra", 
	"Kneza Sime Markovića", 
	"Kneza Stracimira", 
	"Kneza od Semberije", 
	"Kninska", 
	"Knićaninova", 
	"Kovača Jovana Petrovića", 
	"Kovačeva", 
	"Kovačka", 
	"Kovinska", 
	"Kozara", 
	"Kozarčeva", 
	"Kozačinskog", 
	"Kozačka", 
	"Kozjačka", 
	"Kolarska", 
	"Kolarčeva", 
	"Kolačarska", 
	"Kolašinska", 
	"Koledarska", 
	"Kolonija", 
	"Kolonija B fabrike Zmaj", 
	"Kolubarska", 
	"Kolubarske bitke", 
	"Kolubarskih ratnika", 
	"Kolumbova", 
	"Komandanta Stojkovića", 
	"Komandira Cerne", 
	"Komnen barjaktara", 
	"Komovska", 
	"Konavljanska", 
	"Kondina", 
	"Konstantina Jovanovića", 
	"Konstantina Babića", 
	"Konstantina Danila", 
	"Konstantina Kavafija", 
	"Konstantina Lekića", 
	"Konstantina Simonova", 
	"Konstantina Filozofa", 
	"Konfucijeva", 
	"Konfučijeva", 
	"Kopaonička", 
	"Koparska", 
	"Kopernikova", 
	"Kopitareva gradina", 
	"Korbizijeova", 
	"Kordunaška", 
	"Korenička", 
	"Koritnička", 
	"Koriška", 
	"Korijandera", 
	"Kornelija Stankovića", 
	"Kortesarova", 
	"Koruška", 
	"Korčaginova", 
	"Kosančićev venac", 
	"Kosare Cvetković", 
	"Kosačka", 
	"Kosmajska", 
	"Kosmajski prolaz", 
	"Kosmajskog odreda", 
	"Kosovke devojke", 
	"Kosovska", 
	"Kosovskih božura", 
	"Kosovskih junaka", 
	"Kosovskog boja", 
	"Kostajnička", 
	"Koste Jovanovića", 
	"Koste Josipovića", 
	"Koste Abraševića", 
	"Koste Alkovića", 
	"Koste Bogdanovića", 
	"Koste Brankovića", 
	"Koste Vojinovića", 
	"Koste Glavinića", 
	"Koste Dragićevića", 
	"Koste Živkovića", 
	"Koste Miličevića", 
	"Koste Nađa", 
	"Koste Novakovića", 
	"Koste Racina", 
	"Koste Stojanovića", 
	"Koste Taušanovića", 
	"Koste Trifkovića", 
	"Koste Hakmana", 
	"Koste Cukića", 
	"Kostolačka", 
	"Kostreška", 
	"Kotlenička", 
	"Kotorska", 
	"Koče Kapetana", 
	"Koče Popovića", 
	"Košutnjačka", 
	"Konjuh planine", 
	"Kragujevačka", 
	"Kragujevačkih đaka", 
	"Kratka", 
	"Kratohvila Jovana", 
	"Krajiška", 
	"Krajiških brigada", 
	"Kralja Bodina", 
	"Kralja Vladimira", 
	"Kralja Vladislava", 
	"Kralja Vukašina", 
	"Kralja Dragutina", 
	"Kralja Milana", 
	"Kralja Milutina", 
	"Kralja Mihaila Zetskog", 
	"Kralja Mihaila Zetskog 1. deo", 
	"Kralja Mihaila Zetskog 2. deo", 
	"Kralja Nikole", 
	"Kralja Ostoje", 
	"Kralja Petra", 
	"Kralja Petra prvog", 
	"Kralja Radoslava", 
	"Kralja Stefana Tomaša", 
	"Kralja Uroša prvog", 
	"Kraljevačka", 
	"Kraljevačkih žrtava", 
	"Kraljevića Marka", 
	"Kraljice Jelene", 
	"Kraljice Ane", 
	"Kraljice Drage Obrenović", 
	"Kraljice Katarine", 
	"Kraljice Marije", 
	"Kraljice Natalije", 
	"Kranjska", 
	"Kremanska", 
	"Krečarska", 
	"Krešimira Ćosića", 
	"Krešimira Baranovića", 
	"Krznarska", 
	"Krivolačka", 
	"Krivošijska", 
	"Krivudava", 
	"Križanićeva", 
	"Kriste Đorđević", 
	"Kritska", 
	"Kronštatska", 
	"Krojačka", 
	"Krsta Bajića", 
	"Krste Miljkovića", 
	"Krste Sretenovića", 
	"Krsturska", 
	"Kružna", 
	"Kružni put", 
	"Kružni put 5", 
	"Kružni put Kijevo", 
	"Kružni put Rakovica", 
	"Kružni put voždovački", 
	"Krunska", 
	"Krupanjska", 
	"Kruševačka", 
	"Krušedolska", 
	"Krfska", 
	"Ksantija", 
	"Ksenije Jovanović", 
	"Ksenije Atanasijević", 
	"Ksenije Martinov", 
	"Ktitorska", 
	"Kubanska", 
	"Kubertenova", 
	"Kulina Bana", 
	"Kulska", 
	"Kumanovska", 
	"Kumodraška", 
	"Kumodraško groblje", 
	"Kupinski kut", 
	"Kupreška", 
	"Kupska", 
	"Kurirska", 
	"Kursulina", 
	"Kuršumlijska", 
	"Kučajska", 
	"Knjaževačka", 
	"Knjigovezačka", 
	"Labinska", 
	"Labska", 
	"Labuda Šćekovića", 
	"Lagumska", 
	"Ladne vode", 
	"Ladno brdo", 
	"Lazara Avramovića", 
	"Lazara Vozarevića", 
	"Lazara Vujaklije", 
	"Lazara Dimitrijevića", 
	"Lazara Komarčića", 
	"Lazara Kujundžića", 
	"Lazara Mamuzića", 
	"Lazara Petrovića", 
	"Lazara Savatića", 
	"Lazara Sočice", 
	"Lazara Tasića", 
	"Lazara Trifunovića", 
	"Lazara Hilandarca", 
	"Lazarevačka", 
	"Lazarevački drum", 
	"Lazarevićeva", 
	"Laze Jovanovića Porcija", 
	"Laze Dokića", 
	"Laze Kostića", 
	"Laze Lazarevića", 
	"Laze Pačua", 
	"Laze Ristovskog", 
	"Laze Simića", 
	"Laze Stefanovića", 
	"Laze Telečkog", 
	"Lazina", 
	"Lamartinova", 
	"Lapisa", 
	"Lapovska", 
	"Lapovska ulica", 
	"Laudonova", 
	"Lackovićeva", 
	"Lađarska", 
	"Levskog", 
	"Ledi Pedžet", 
	"Ledinačka", 
	"Leke kapetana", 
	"Leksa Saičića", 
	"Lenke Marinković", 
	"Lenke Rabasović", 
	"Lenkina", 
	"Leona Koena", 
	"Leonarda Da Vinčija", 
	"Lepe Stamenković", 
	"Lepenička", 
	"Lepenskog vira", 
	"Leposave Vujošević", 
	"Leposave Mihajlović", 
	"Leposave Miljković", 
	"Leskovačka", 
	"Lesnovska", 
	"Letenka", 
	"Letićeva", 
	"Letnja", 
	"Lešačka", 
	"Lešnikova", 
	"Livadska", 
	"Livačka", 
	"Livanjska", 
	"Liksuri", 
	"Limska", 
	"Lindenmajerova", 
	"Lipa", 
	"Lipak", 
	"Lipar", 
	"Lipetska", 
	"Lipovačka", 
	"Listopadna", 
	"Ličinska", 
	"Lička", 
	"Ličkih brigada", 
	"Lijačka", 
	"Lovačka", 
	"Lovranska", 
	"Loznička", 
	"Lokrumska", 
	"Lole Novaković", 
	"Lole Ribara", 
	"Lomina", 
	"Lončarska", 
	"Lošinjska donja", 
	"Lojze Dolinara", 
	"Lugarska", 
	"Lugovačka", 
	"Lugomirska", 
	"Lužička", 
	"Luke Ćelovića Trebinjca", 
	"Luke Vojvodića", 
	"Luke Vukalovića", 
	"Luke Spasojevića", 
	"Lukijana Mušickog", 
	"Luneta Milovanovića", 
	"Lučanska", 
	"Luštička", 
	"Luja Adamiča", 
	"Luja Daviča", 
	"Mavrovska", 
	"Mage Magazinović", 
	"Magelanova", 
	"Magistratski trg", 
	"Maglajska", 
	"Maglićka", 
	"Magnolija", 
	"Madridska", 
	"Mažuranićeva", 
	"Makarijeva", 
	"Makedonska", 
	"Makenzijeva", 
	"Makiška", 
	"Makiška kolonija Kosmaj", 
	"Maksima Đurovića", 
	"Maksima Brankovića", 
	"Maksima Brankovića 1. deo", 
	"Maksima Gorkog", 
	"Maksima Trpkovića", 
	"Mala", 
	"Mala česma", 
	"Malvine Hofman", 
	"Male međe 28. nova", 
	"Male međe 29. nova", 
	"Male međe 30. nova", 
	"Male međe 31. nova", 
	"Male međe 32. nova", 
	"Male međe 33. nova", 
	"Male međe 34. nova", 
	"Male međe 35. nova", 
	"Male međe 36. nova", 
	"Male međe 37. nova", 
	"Male međe 38. nova", 
	"Male međe 39. nova", 
	"Male međe 40. nova", 
	"Male međe 41. nova", 
	"Male međe 42. nova", 
	"Male međe 43. nova", 
	"Male međe 44. nova", 
	"Male međe 45. nova", 
	"Male međe 46. nova", 
	"Male međe 47. nova", 
	"Male međe 48. nova", 
	"Male međe nova 39.", 
	"Male međe nova 40.", 
	"Male stepenice", 
	"Malena", 
	"Maleška", 
	"Malinarska", 
	"Malo silazno stepenište", 
	"Malo stepenište", 
	"Malog Radojice", 
	"Malozabranska", 
	"Manakijeva", 
	"Manasijeva", 
	"Manastirine", 
	"Manastirska", 
	"Mandrinska", 
	"Maneta Bajića", 
	"Mare Taborske", 
	"Mariborska", 
	"Marina", 
	"Marine Veličković", 
	"Marine Koljubajeve", 
	"Marinka Benzona", 
	"Marinka Šebeza", 
	"Marička", 
	"Marijane Gregoran", 
	"Marijane Gregoran 1. prolaz", 
	"Marije Bursać", 
	"Marije Vučetić", 
	"Marije Zibold", 
	"Marije Kalas", 
	"Marije Mirčetić", 
	"Marije Crnobori", 
	"Marka Končara-Bure", 
	"Marka Leka", 
	"Marka Markovića", 
	"Marka Milanovića", 
	"Marka Miljanova", 
	"Marka Nikolića", 
	"Marka Oreškovića", 
	"Marka Peričina Kamenjara", 
	"Marka Pola", 
	"Marka Ristića", 
	"Marka Stojkovića", 
	"Marka Tajčevića", 
	"Marka Todorovića", 
	"Marka Hristića", 
	"Marka Čelebonovića", 
	"Marka Šagala", 
	"Markesova", 
	"Markonijeva džada", 
	"Marte Jorgović", 
	"Martina Lutera Kinga", 
	"Martina Paluške", 
	"Marulićeva", 
	"Marčanska", 
	"Maršala Birjuzova", 
	"Maršala Tita", 
	"Marjanovićeva", 
	"Masarikov trg", 
	"Masarikova", 
	"Matavuljeva", 
	"Mataruška", 
	"Mate Miloševića", 
	"Mate Parlova", 
	"Matejička", 
	"Matice srpske", 
	"Matičanska", 
	"Matije Ambrožića", 
	"Matije Bana", 
	"Matije Vukovića", 
	"Matije Ivanića", 
	"Matoševa", 
	"Matrozova", 
	"Mahmuta Ibrahimpašića", 
	"Mačvanska", 
	"Mačkov kamen", 
	"Maja Glave", 
	"Majakovskog", 
	"Majdanpečka", 
	"Majdanska", 
	"Majdanska Čukarica", 
	"Maje Dimitrijević", 
	"Maje Zlatogorke", 
	"Maje Čučković Draškić", 
	"Majevička", 
	"Majke Jevrosime", 
	"Majke Jugovića", 
	"Majke Angeline", 
	"Majke Kujundžić", 
	"Majora Jagodića", 
	"Majora Aleksandra Mišića", 
	"Majora Branka Vukosavljevića", 
	"Majora Dobrosava Tešića", 
	"Majora Zorana Radosavljevića", 
	"Majora Ive Fregla", 
	"Majora Ilića", 
	"Majora Milana Malnarića", 
	"Majora Mihaila Madžarevića", 
	"Majora Nikolajevića", 
	"Majora Omera Mehića", 
	"Majorska", 
	"Majska", 
	"Maljenska", 
	"Meandarska", 
	"Megarska", 
	"Meda Pucića", 
	"Medakovićeva", 
	"Medačka", 
	"Medlinška", 
	"Mezijska", 
	"Merošinska", 
	"Metalska", 
	"Metohijska", 
	"Mehaničarska", 
	"Mehmeda Sokolovića", 
	"Meše Selimovića", 
	"Meštrovićeva", 
	"Migela Anhela Asturijasa", 
	"Mike Alasa", 
	"Mike Ilića", 
	"Mike Mitrovića", 
	"Mikenska", 
	"Miklošićeva", 
	"Mila Vojinovića", 
	"Mila Milunovića", 
	"Miladina Petrovića", 
	"Milana Đurića", 
	"Milana Jovanovića", 
	"Milana Ćurčina", 
	"Milana Antonovića", 
	"Milana Bartoša", 
	"Milana Blagojevića Španca", 
	"Milana Bogdanovića", 
	"Milana Budimira", 
	"Milana Vape", 
	"Milana Vukosa", 
	"Milana Vujaklije", 
	"Milana Vujovića", 
	"Milana Galića", 
	"Milana Gajića", 
	"Milana Gligorijevića", 
	"Milana Gligorijevića 1. prilaz", 
	"Milana Grola", 
	"Milana Dedinca", 
	"Milana Delića", 
	"Milana Živkovića", 
	"Milana Zečara", 
	"Milana Zlokovića", 
	"Milana Ilića", 
	"Milana Kapetanovića", 
	"Milana Kašanina", 
	"Milana Konjovića", 
	"Milana Kurepe", 
	"Milana Kuča", 
	"Milana Milićevića", 
	"Milana Milovanovića", 
	"Milana Mijalkovića", 
	"Milana Mijatovića", 
	"Milana Mladenovića", 
	"Milana Muškatirovića", 
	"Milana Munjasa", 
	"Milana Nedeljkovića", 
	"Milana Praizovića", 
	"Milana Predića", 
	"Milana Puzića", 
	"Milana Rakića", 
	"Milana Raspopovića", 
	"Milana Rešetara", 
	"Milana Ristanovića", 
	"Milana S. Minića", 
	"Milana Srdoča", 
	"Milana Stanivukovića", 
	"Milana Stepanovića Matroza", 
	"Milana Stojkovića", 
	"Milana Tankosića", 
	"Milana Tomića", 
	"Milana Uzelca", 
	"Milana Šarca", 
	"Milane Čupić", 
	"Milanke Kljajić", 
	"Milanovačka", 
	"Mile Jevtović", 
	"Mile Dimitrijević", 
	"Mile Dimić", 
	"Mileve Marić Ajnštajn", 
	"Mileve Simić", 
	"Milene Pavlović Barili", 
	"Milene Čupić", 
	"Milenka Verkića", 
	"Milenka Vesnića", 
	"Milenka Zablaćanskog", 
	"Milenka Stojkovića", 
	"Milenka Turudića", 
	"Milentija Popovića", 
	"Milete Jakšića", 
	"Milete Magaraševića", 
	"Mileševska", 
	"Milivoja Živanovića", 
	"Milivoja Miće Tomića", 
	"Milivoja Nenadovića", 
	"Milivoja Pavlovića", 
	"Milivoja Perovića", 
	"Milinka Kušića", 
	"Milisava Đurovića", 
	"Milisava Dakića", 
	"Milisava Lutovca", 
	"Milice Janković", 
	"Milice Babić Jovanović", 
	"Milice Milojković", 
	"Milice Miljanov", 
	"Milice Ninković", 
	"Milice Rakić", 
	"Milice Ribnikar", 
	"Milice Srpkinje", 
	"Milice Stojadinović Srpkinje", 
	"Milice Hrebeljanović", 
	"Milice Šuvaković", 
	"Milića Marinovića", 
	"Milića Rakića", 
	"Milića od Mačve", 
	"Milićeva", 
	"Milke Bosnić", 
	"Milke Grgurove", 
	"Milke Lukić", 
	"Milovana Jankovića", 
	"Milovana Vidakovića", 
	"Milovana Glišića", 
	"Milovana Marinkovića", 
	"Milovana Markovića", 
	"Milovana Milovanovića", 
	"Milovana Nićiforovića", 
	"Milovana Čelebića", 
	"Milovana Šaranovića", 
	"Milomira Stanišića", 
	"Milorada Jankovića Doce", 
	"Milorada Jovanovića", 
	"Milorada Ćirića", 
	"Milorada Bate Mihailovića", 
	"Milorada Bondžulića", 
	"Milorada Gavrilovića", 
	"Milorada Dimitrijevića", 
	"Milorada Draškovića", 
	"Milorada Ekmečića", 
	"Milorada Milosavljevića", 
	"Milorada Mitrovića", 
	"Milorada Miškovića", 
	"Milorada Pavića", 
	"Milorada Petrovića", 
	"Milorada Popovića", 
	"Milorada Ruvidića", 
	"Milorada Umjenovića", 
	"Milorada Šapčanina", 
	"Milosava Vlajića", 
	"Miloša Bandića", 
	"Miloša Bajića", 
	"Miloša Bogićevića", 
	"Miloša Bradića", 
	"Miloša Golubovića", 
	"Miloša Žutića", 
	"Miloša Zečevića", 
	"Miloša Marića", 
	"Miloša Matijevića", 
	"Miloša Miloševića", 
	"Miloša Milojevića", 
	"Miloša Milutinovića", 
	"Miloša Pocerca", 
	"Miloša Savkovića", 
	"Miloša Savčića", 
	"Miloša Sarića", 
	"Miloša Svetića", 
	"Miloša Svilara", 
	"Miloša Tenkovića", 
	"Miloša Crnjanskog", 
	"Milošev kladenac", 
	"Milošev potok", 
	"Miloja Đaka", 
	"Miloja Vasića", 
	"Miloja Zakića", 
	"Miloja Pavlovića", 
	"Miloja Stojanovića", 
	"Milojka Vucelića", 
	"Miluna Marovića", 
	"Milunke Savić", 
	"Milutina Đurišića", 
	"Milutina Bojića", 
	"Milutina Butkovića", 
	"Milutina Garašanina", 
	"Milutina Kukanjca", 
	"Milutina Milankovića", 
	"Milutina Paunovića", 
	"Milutina Stanojevića", 
	"Milutina Stefanovića", 
	"Milutina Uskokovića", 
	"Milutina Čolića", 
	"Mine Vukomanović", 
	"Mine Karadžić", 
	"Miodraga Avramovića", 
	"Miodraga Bulatovića", 
	"Miodraga Živanova", 
	"Miodraga Živkovića", 
	"Miodraga Ibrovca", 
	"Miodraga Ilića Belog", 
	"Miodraga Mijovića Kanta", 
	"Miodraga Nikolića", 
	"Miodraga Pavlovića", 
	"Miodraga Petrovića", 
	"Miodraga Petrovića Čkalje", 
	"Miodraga Protića", 
	"Miomira Vukobratovića", 
	"Miomira Denića", 
	"Mira Popare", 
	"Mire Papić", 
	"Mirijevska", 
	"Mirijevski Venac", 
	"Mirijevski bulevar", 
	"Mirijevski venac", 
	"Mirijevsko brdo", 
	"Mirka Banjevića", 
	"Mirka Lukovića", 
	"Mirka Milojkovića", 
	"Mirka Poštića", 
	"Mirka Sandića", 
	"Mirovačka", 
	"Mirosavljeva", 
	"Miroslava Jovanovića", 
	"Miroslava Antića", 
	"Miroslava Bijelića", 
	"Miroslava Veličkovića", 
	"Miroslava Krleže", 
	"Miroslava Mike Mikerovića", 
	"Miroslava Radivojevića", 
	"Miroslava Radojčića", 
	"Miroslava Tirša", 
	"Miroslava Čangalovića", 
	"Miročka", 
	"Mirča Aceva", 
	"Mirjane Kodžić", 
	"Mis Irbijeve", 
	"Misije Halijard", 
	"Mite Rakića", 
	"Mite Ružića", 
	"Mite Cenića", 
	"Mitkov kladenac", 
	"Mitra Bakića", 
	"Mitra Kostića", 
	"Mitrovačka", 
	"Mitrovdanska", 
	"Mitrovićev prolaz", 
	"Mitropolita Mihaila", 
	"Mitropolita Mraovića", 
	"Mitropolita Pavla Nenadovića", 
	"Mitropolita Petra", 
	"Mitropolita Stratimirovića", 
	"Mitrofana Hilandarca", 
	"Mihaila Đurića", 
	"Mihaila Avramovića", 
	"Mihaila Bogićevića", 
	"Mihaila Bulgakova", 
	"Mihaila Vukše", 
	"Mihaila Vujića", 
	"Mihaila Gavrilovića", 
	"Mihaila Ivanjikova", 
	"Mihaila Mike Jankovića", 
	"Mihaila Milovanovića", 
	"Mihaila Petrova", 
	"Mihaila Polita Desančića", 
	"Mihaila Simića", 
	"Mihaila Stanojevića", 
	"Mihaila Terzibašića", 
	"Mihaila Todorovića", 
	"Mihaila Šuškalovića", 
	"Mihajla Andrejevića", 
	"Mihajla Bandura", 
	"Mihajla Bate Paskaljevića", 
	"Mihajla Valtrovića", 
	"Mihajla Viktorovića", 
	"Mihajla Kostića Pljake", 
	"Mihajla Lalića", 
	"Mihajla Markovića", 
	"Mihajla Mikašinovića", 
	"Mihajla Petrovića", 
	"Mihajla Pupina", 
	"Mihajla Švrake", 
	"Mihaljevačka", 
	"Mihizova", 
	"Mihovila Logara", 
	"Miholjska", 
	"Mickijevičeva", 
	"Mišarska", 
	"Miše Blama", 
	"Miše Vujića", 
	"Miše Dimitrijevića", 
	"Miše Zarića", 
	"Miše Popovića", 
	"Miška Jovanovića", 
	"Miška Kranjca", 
	"Mijata Mijatovića", 
	"Mijačka", 
	"Mije Aleksića", 
	"Mije Kovačevića", 
	"Miljakovačka", 
	"Miljakovačke livade", 
	"Miljakovačke staze", 
	"Miljakovačke šume", 
	"Miljakovački vinogradi", 
	"Miljakovački izvori", 
	"Miljakovačko brdo", 
	"Miljana Miljanića", 
	"Minje Vojvodića", 
	"Minje Dedića", 
	"Mića Radakovića", 
	"Miće Orlovića", 
	"Miće Popovića", 
	"Midžorska", 
	"Mlavska", 
	"Mlade Bosne", 
	"Mladena Josića", 
	"Mladena Žujovića", 
	"Mladena Milovanovića", 
	"Mladena Mitrića", 
	"Mladena Stojanovića", 
	"Mladenovačka", 
	"Mladih gorana", 
	"Mlatišumina", 
	"Mlinarska", 
	"Mlinska", 
	"Mozerova", 
	"Mokranjčeva", 
	"Mokri Sebeš", 
	"Mokroluška", 
	"Molerova", 
	"Momačka", 
	"Mome Dimića", 
	"Mome Kapora", 
	"Mome Markovića", 
	"Mome Stanojlovića", 
	"Momčila Radivojevića", 
	"Momčila Tapavice", 
	"Momčila Čedića", 
	"Moravička", 
	"Moravska", 
	"Morinjska", 
	"Mornarska", 
	"Mosorska", 
	"Most Gazela", 
	"Most na Adi", 
	"Mostarska", 
	"Motokros staza", 
	"Mocartova", 
	"Mojkovačka", 
	"Mrakovička", 
	"Mraovića sokače", 
	"Mrcinište nova 28", 
	"Muminovačka", 
	"Murmanska", 
	"Murska", 
	"Musorgskog", 
	"Mustafe Golubića", 
	"Mutapova", 
	"Mutimirova", 
	"Mušickog", 
	"Nabokovljeva", 
	"Nade Dimić", 
	"Nade Naumović", 
	"Nade Purić", 
	"Nade Purić prilaz 1", 
	"Nadežde Petrović", 
	"Nake Spasić", 
	"Namesnika Protića", 
	"Nandora Glida", 
	"Narednika Grujice Stankovića", 
	"Narednika Dragutina Radakovića", 
	"Narednička", 
	"Narodnih heroja", 
	"Narodnog fronta", 
	"Narcisa", 
	"Naselje Ekonomije br. 1", 
	"Naselje Zemun polje Mala pruga", 
	"Naselje Zemun polje mala pruga 1. deo", 
	"Naselje Zemun polje mala pruga 2. deo", 
	"Nasip", 
	"Nastićeva", 
	"Natalije Bjelajac", 
	"Natalije Dubajić", 
	"Natalije Munk", 
	"Natalijine ramonde", 
	"Nataše Bošković", 
	"Natoševićeva", 
	"Nea Pendeli", 
	"Nebojše Đukelića", 
	"Nebojše Dukića", 
	"Nebojše Markovića", 
	"Nebojšina", 
	"Nevena", 
	"Nevenke Urbanove", 
	"Nevesinjska", 
	"Negovana Ljubinkovića", 
	"Negotinska", 
	"Nede Spasojević", 
	"Nedeljka Gvozdenovića", 
	"Nedeljka Košanina", 
	"Nedeljka Čabrinovića", 
	"Neznanog junaka", 
	"Nemanjina", 
	"Nemirović Dančenka", 
	"Nenada Golubovića", 
	"Nenada Manojlovića", 
	"Nenadovićeva", 
	"Nenadovićeva ulica", 
	"Neretvanska", 
	"Nerodimska", 
	"Nestora Žučnoga", 
	"Nestorovićeva", 
	"Nehruova", 
	"Nika Strugara 1. prilaz", 
	"Nike Maksimovića", 
	"Nikinačka", 
	"Nikice Popovića", 
	"Nikodima Milaša", 
	"Nikola Bižumića", 
	"Nikolaja Berđajeva", 
	"Nikolaja Gogolja", 
	"Nikolaja Kravcova", 
	"Nikolaja Krasnova", 
	"Nikolaja Ostrovskog", 
	"Nikolaja R. Korsakova", 
	"Nikolaja Saltikova", 
	"Nikolaja Hartviga", 
	"Nikolajevićeva", 
	"Nikole Đurkovića", 
	"Nikole Ćuka", 
	"Nikole Altomanovića", 
	"Nikole Baloga", 
	"Nikole Beševića", 
	"Nikole Vulića", 
	"Nikole Vučete", 
	"Nikole Grulovića", 
	"Nikole Demonje", 
	"Nikole Dobrovića", 
	"Nikole Doksata", 
	"Nikole Karaklajića", 
	"Nikole Kareva", 
	"Nikole Kurelića", 
	"Nikole Marakovića", 
	"Nikole Milića", 
	"Nikole Miloševića", 
	"Nikole Miljanovića", 
	"Nikole Nestorovića", 
	"Nikole Nikolića", 
	"Nikole P. Stojanovića", 
	"Nikole Rašića", 
	"Nikole Ribarića", 
	"Nikole Simića", 
	"Nikole Sovilja", 
	"Nikole Spasića", 
	"Nikole Stamenkovića", 
	"Nikole Stefanovića", 
	"Nikole Strineke", 
	"Nikole Suknjarevića Prike", 
	"Nikole Tanurdžića", 
	"Nikole Tesle", 
	"Nikole Čupića", 
	"Nikše Gradija", 
	"Nikše Stipčevića", 
	"Nikšićka", 
	"Nilsa Bora", 
	"Nine Kirsanove", 
	"Ninka Petrovića", 
	"Nišavska", 
	"Niška", 
	"Nićifora Dučića", 
	"Nićifora Ninkovića", 
	"Nova 109", 
	"Nova 110", 
	"Nova 113", 
	"Nova 114", 
	"Nova 17", 
	"Nova 2", 
	"Nova 47", 
	"Nova 501", 
	"Novaka Atanackovića", 
	"Novaka Novaka", 
	"Novakova", 
	"Novi avalski put", 
	"Novice Mitića", 
	"Novice Tadića", 
	"Novice Cerovića", 
	"Novobeogradskih graditelja", 
	"Novobrdska", 
	"Novovaroška", 
	"Novogradska", 
	"Novopazarska", 
	"Novosadska", 
	"Nodilova", 
	"Norveška", 
	"Nušićeva", 
	"Obala kralja Aleksandra I Karađorđevića", 
	"Obala majora Dragutina Gavrilovića", 
	"Obala jasenovačkih žrtava", 
	"Obalskih radnika", 
	"Obedska bara", 
	"Obilaznica oko Beograda", 
	"Obilićev venac", 
	"Oblakovska", 
	"Obrenovačka", 
	"Obrenovački drum", 
	"Obućarska", 
	"Ovčarska", 
	"Ogista Bopa", 
	"Odabašićeva", 
	"Odeska", 
	"Ozrenska", 
	"Okretnica", 
	"Oktobarska", 
	"Olge Jevrić", 
	"Olge Jovanović", 
	"Olge Jovičić", 
	"Olge Jojić", 
	"Olge Alkalaj", 
	"Olge Divac", 
	"Olge Ivanović", 
	"Olge Ilić Hristilić", 
	"Olge Milošević", 
	"Olge Petrov", 
	"Olge Spiridonović", 
	"Oliv King", 
	"Olivere Marković", 
	"Oliverina", 
	"Olimpijska", 
	"Olimpijskih igara", 
	"Olimpska", 
	"Omiška", 
	"Omladinska", 
	"Omladinskih brigada", 
	"Omladinsko šetalište", 
	"Omorika", 
	"Omorička", 
	"Onisima Popovića", 
	"Opančarska", 
	"Oparićka", 
	"Opatijska", 
	"Oplenačka", 
	"Orahova", 
	"Orahovog lista", 
	"Orahovska", 
	"Oračka", 
	"Orašačka", 
	"Orvelova", 
	"Orelska", 
	"Orlovatska", 
	"Orlovačka", 
	"Orlovića Pavla", 
	"Orlovska", 
	"Orsona Velsa", 
	"Orfelinova", 
	"Oskara Daviča", 
	"Oskara Danona", 
	"Oslobodilaca Rakovice", 
	"Oslobođenja", 
	"Oslobođenja 5. deo", 
	"Osmana Đikića", 
	"Osme crnogorske brigade", 
	"Osmog marta", 
	"Osmog septembra", 
	"Ostoje Živkovića", 
	"Ostroška", 
	"Otokara Keršovanija", 
	"Otona Župančiča", 
	"Otranska", 
	"Oficirska kolonija", 
	"Oficirska kolonija 1. deo", 
	"Oficirska kolonija 2. deo", 
	"Oficirska kolonija 3. deo", 
	"Oficirska kolonija 4. deo", 
	"Oficirska kolonija 5. deo", 
	"Oficirska kolonija 6. deo", 
	"Ohridska", 
	"Oštreljska", 
	"Ošljačka", 
	"Olje Ivanjicki", 
	"Odžačarska", 
	"Pabla Nerude", 
	"Pavla Jurišića Šturma", 
	"Pavla Bakića", 
	"Pavla Bogatinčevića", 
	"Pavla Vasića", 
	"Pavla Vujevića", 
	"Pavla Vujisića", 
	"Pavla Zarića", 
	"Pavla Labata", 
	"Pavla Minčića", 
	"Pavla Pavlovića", 
	"Pavla Popovića", 
	"Pavla Radovanovića", 
	"Pavla Savića", 
	"Pavla Sofrića", 
	"Pavla Ugrinova", 
	"Pavla Cukića", 
	"Padejska", 
	"Padinska", 
	"Pazinska", 
	"Pazovački put", 
	"Pakračka", 
	"Palackova", 
	"Palilulska", 
	"Palisadska 1. deo", 
	"Palisadska 2. deo", 
	"Palisadska prilaz dva", 
	"Palisadska prilaz jedan", 
	"Palih boraca", 
	"Palićka", 
	"Palmira Toljatija", 
	"Palmotićeva", 
	"Pana Đukića", 
	"Panajota Papakostopulosa", 
	"Pante Jakovljevića", 
	"Pante Mihajlovića", 
	"Pante Srećkovića", 
	"Pante Tutundžića", 
	"Pante Filipovića", 
	"Pančevačka", 
	"Pančevački most", 
	"Pančevački put", 
	"Pančina", 
	"Pančićeva", 
	"Paraćinska", 
	"Pariska", 
	"Pariske komune", 
	"Partizanska", 
	"Partizanske avijacije", 
	"Partizanske vode", 
	"Partizanski blok ulica 1.", 
	"Partizanski blok ulica 2.", 
	"Partizanski blok ulica 3.", 
	"Partizanskih učitelja", 
	"Pasaž Karla Maldena", 
	"Pasternakova", 
	"Pasterova", 
	"Pastira Kostje", 
	"Pastirska", 
	"Patrisa Lumumbe", 
	"Patrijarha Joanikija", 
	"Patrijarha Varnave", 
	"Patrijarha Gavrila", 
	"Patrijarha Dimitrija", 
	"Patrijarha Šakabente", 
	"Patrijarha srpskog Savatija", 
	"Paula Klea", 
	"Pauline Matijević", 
	"Paunova", 
	"Paunova drugi deo", 
	"Pašinac", 
	"Paška Vučetića", 
	"Pašmanska", 
	"Paštrovićeva", 
	"Pašnjačka", 
	"Paje Jovanovića", 
	"Paje Adamova", 
	"Pajsijeva", 
	"Peka Pavlovića", 
	"Peka Tepavčevića", 
	"Pekarska", 
	"Pera Ćetkovića", 
	"Pera Ćetkovića-prolaz", 
	"Pera Slijepčevića", 
	"Pere Velimirovića", 
	"Pere Veljkovića", 
	"Pere Kosorića", 
	"Pere Segedinca", 
	"Pere Todorovića", 
	"Peristerska", 
	"Perice Ivanovića", 
	"Perside Milenković", 
	"Pesnička", 
	"Pete kozarske", 
	"Petera Urbana", 
	"Petefijeva", 
	"Petkov kladenac", 
	"Petra Đurkovića", 
	"Petra Jovanovića", 
	"Petra Jovovića", 
	"Petra Džadžića", 
	"Petra Anagnostija", 
	"Petra Banićevića", 
	"Petra Bajalovića", 
	"Petra Gvojića", 
	"Petra Dobrovića", 
	"Petra Drapšina", 
	"Petra Kovačevića", 
	"Petra Kolendića", 
	"Petra Kočića", 
	"Petra Konjovića", 
	"Petra Kralja", 
	"Petra Krstića", 
	"Petra Lekovića", 
	"Petra Lubarde", 
	"Petra Lupe", 
	"Petra Martinovića", 
	"Petra Mećave", 
	"Petra Mrkonjića", 
	"Petra Obradovića", 
	"Petra Pavlovića", 
	"Petra Pešića", 
	"Petra Preradovića", 
	"Petra Serafimovića", 
	"Petra Stojanovića", 
	"Petra Tatića", 
	"Petra Ubavkića", 
	"Petra Čajkovskog", 
	"Petra Škundrića", 
	"Petrarkina", 
	"Petrac kanal", 
	"Petrijina", 
	"Petrinjska", 
	"Petrovaradinska", 
	"Petrovačka", 
	"Petrovdanska", 
	"Petrovdanska 1. prilaz", 
	"Petrogradska", 
	"Petunija", 
	"Pešački most „Stankom“", 
	"Pešački prolaz Albanija", 
	"Pešački prolaz Atina", 
	"Pešački prolaz Zeleni venac", 
	"Pešački prolaz Nušićeva", 
	"Pešački prolaz RK Beograd", 
	"Pešački prolaz Sajam", 
	"Pešterska", 
	"Peščarska", 
	"Peđa Leovca", 
	"Peđe Milosavljevića", 
	"Pećinačka", 
	"Pećka", 
	"Pećska", 
	"Piva Karamatijevića", 
	"Pivljanina Baja", 
	"Pilota Mihaila Petrovića", 
	"Pilota Ratka Jovanovića", 
	"Pilotska", 
	"Pinkijeva", 
	"Pionirska", 
	"Pirandelova", 
	"Pirotska", 
	"Piroćančeva", 
	"Pit-stop", 
	"Pita Maravića", 
	"Pijaca Karaburma", 
	"Piljarska", 
	"Plavska", 
	"Plandiška", 
	"Planinska", 
	"Planinskih borova", 
	"Platana", 
	"Platanov hlad", 
	"Plato Đoke Vještice", 
	"Plato Ljubomira Mucija Draškića", 
	"Plato Bogdana Babića", 
	"Plato Dimitrija Tucovića", 
	"Plato Nenada Radulovića – Neše Leptira", 
	"Plato Raše Livade", 
	"Plato Slobodana Jovanovića", 
	"Plato Soje Jovanović", 
	"Plato kod stepeništa", 
	"Plzenjska", 
	"Plitvička", 
	"Povlenska", 
	"Povlenskih vrhova", 
	"Pogranične čete", 
	"Podavalska", 
	"Podgorička", 
	"Podmorničara Đorđa Mitrovića", 
	"Podravska", 
	"Podrugovićeva", 
	"Podunavska", 
	"Podujevska", 
	"Poenkareova", 
	"Požarevačka", 
	"Požeška", 
	"Pola Gogena", 
	"Poleksije Todorović", 
	"Politova", 
	"Pološka", 
	"Pomoravska", 
	"Pop Lukina", 
	"Pop Stojanova", 
	"Popova bara nova 3.", 
	"Popova bara nova 301", 
	"Popova bara nova 302", 
	"Popova bara nova 303", 
	"Popova bara nova 304", 
	"Popova bara nova 306.", 
	"Popsova", 
	"Porečka", 
	"Porodice Blagojević", 
	"Porodice Valožić", 
	"Porodice Nikolić", 
	"Porodice Petković", 
	"Porodice Spasojević", 
	"Porodice Stepanović", 
	"Porodice Stojković", 
	"Porodice Trajković", 
	"Porodice Trajković 4. deo", 
	"Poručnika Spasića i Mašere", 
	"Poručnička", 
	"Posavinska", 
	"Posavska", 
	"Posavskih partizana", 
	"Poslastičarska", 
	"Postojnska", 
	"Potok", 
	"Potočka", 
	"Pocerinska", 
	"Poljane", 
	"Poljoprivredno dobro 13. maj", 
	"Prava", 
	"Prahovska", 
	"Praška", 
	"Praška 2. red", 
	"Prve balkanske radio-antene", 
	"Prve pruge", 
	"Prve radio-stanice", 
	"Prve šumadijske brigade", 
	"Prvoboraca", 
	"Prvog maja", 
	"Prvog novembra", 
	"Prvog sremskog odreda", 
	"Prvomajska", 
	"Prvomajsko sokače", 
	"Pregrevica", 
	"Predraga Vasića", 
	"Predraga Lakovića", 
	"Predraga Manojlovića", 
	"Predraga Milojevića", 
	"Predraga Simića", 
	"Predraga Tasovca", 
	"Predraga Tomića", 
	"Preka", 
	"Prekobrojnih pukova", 
	"Prekonoška", 
	"Prepolačka", 
	"Preradovićeva", 
	"Prespanska", 
	"Preševska", 
	"Prešernova", 
	"Pribojska", 
	"Pribojske stepenice", 
	"Prizrenska", 
	"Prilepska", 
	"Prilučka", 
	"Primirja", 
	"Primorska", 
	"Primoštenska", 
	"Primućura Žarka", 
	"Princeze Olivere", 
	"Prištinska", 
	"Prijedorska", 
	"Prijepoljska", 
	"Provalijska", 
	"Prozorska", 
	"Prokop 1. sokače", 
	"Prokop 2. sokače", 
	"Prokop 3. sokače", 
	"Prokupačka", 
	"Prolaz 5", 
	"Proleterska", 
	"Prolećna", 
	"Prolećnog cveća", 
	"Prolomska", 
	"Prominska", 
	"Prote Đurića", 
	"Prote Brane Polkića", 
	"Prote Mateje", 
	"Prote Milana Smiljanića", 
	"Prote Milorada Pavlovića", 
	"Profesora Koste Vujića", 
	"Profesora Mihaila Đurića", 
	"Pružni put", 
	"Prnjavorska", 
	"Psačka", 
	"Ptujska", 
	"Pukovnika Bacića", 
	"Pukovnika Milenka Pavlovića", 
	"Pukovnika Petra Mišića", 
	"Pukovnika Pejovića", 
	"Pukovnika Purića", 
	"Pukovnička", 
	"Pupinov most", 
	"Pupinova", 
	"Pusino sokače", 
	"Pustorečka", 
	"Put za Ada Huju", 
	"Put za Resnik", 
	"Put za kamenolom", 
	"Puškinova", 
	"Pčelarska", 
	"Pčinjska", 
	"Pšenička", 
	"Pjarona de Mondezira", 
	"Pjera Križanića", 
	"Pjera de Kubertena", 
	"Pljakina", 
	"Pljevaljska", 
	"Plješevička", 
	"Rabina Alkalaja", 
	"Rableova", 
	"Ravanička", 
	"Rada Drainca", 
	"Rada Neimara", 
	"Rada Ostojića", 
	"Radavačka", 
	"Radanska", 
	"Radaljska", 
	"Rade Vranješević", 
	"Rade Kondića", 
	"Rade Končara", 
	"Radenka Miševića", 
	"Radeta Krapovića", 
	"Radeta Markovića", 
	"Radete Stankovića", 
	"Radivoja Koraća", 
	"Radivoja Lole Đukića", 
	"Radivoja Markovića", 
	"Radivoja Mitrovića", 
	"Radivoja Rakonjca", 
	"Radmile Jović", 
	"Radmile Guteše", 
	"Radmile Milanović Šnajder", 
	"Radmile Savićević", 
	"Radnih akcija", 
	"Radnička", 
	"Radovana Ćosića", 
	"Radovana Babića", 
	"Radovana Dragovića", 
	"Radovana Miloševića", 
	"Radovana Samardžića", 
	"Radovana Simića Cige", 
	"Radomira Kovačevića", 
	"Radomira Markovića", 
	"Radomira Reljića", 
	"Radosava Ljumovića", 
	"Radoslava Bokšića", 
	"Radoslava Vesnića", 
	"Radoslava Grujića", 
	"Radošinska", 
	"Radoja Dakića", 
	"Radoja Domanovića", 
	"Radoja Prvulovića", 
	"Radojice Stankovića", 
	"Radojke Lakić", 
	"Razvodnička", 
	"Rakovački potok", 
	"Rakovička", 
	"Rakovičkih rudara", 
	"Ramadanska", 
	"Ramska", 
	"Raniluška", 
	"Ranka Žeravice", 
	"Ranka Tajsića", 
	"Rankeova", 
	"Rasinska", 
	"Rastislava Jovića", 
	"Rastislava Marića", 
	"Rastka Petrovića", 
	"Ratarska", 
	"Ratarski put", 
	"Ratislave Slave Zagorčić", 
	"Ratka Mitrovića", 
	"Ratka Pavlovića", 
	"Ratka Resanovića", 
	"Ratka Resanovića 2. deo", 
	"Ratka Resanovića 3. deo", 
	"Ratka Resanovića drugi deo", 
	"Ratka Resanovića treći deo", 
	"Ratka Sarića", 
	"Ratka Sofjanića", 
	"Račkoga", 
	"Raše Plaovića", 
	"Raška", 
	"Raška Dimitrijevića", 
	"Rađevska", 
	"Rajačićeva", 
	"Rajačka", 
	"Rajićeva", 
	"Rajka Lešjanina", 
	"Rajka Mitića", 
	"Rajka Ružića", 
	"Rajka od Rasine", 
	"Rajkova", 
	"Rajskih ptica", 
	"Rajsko sokače", 
	"Raljska", 
	"Rebeke Vest", 
	"Rekovačka", 
	"Rembrantova", 
	"Remetinska", 
	"Renartova", 
	"Rene Magrita", 
	"Repiška", 
	"Republička", 
	"Resavska", 
	"Resavskih humova", 
	"Resnička", 
	"Resnički put", 
	"Reljina", 
	"Reljkovićeva", 
	"Ribarčeva", 
	"Ribnička", 
	"Ribnjak Mika Alas", 
	"Rige od Fere", 
	"Rimska", 
	"Risanska", 
	"Risovačka", 
	"Riste Vukanovića", 
	"Riste Marjanovića", 
	"Riste Nikolića", 
	"Riste Stefanovića", 
	"Ristin potok", 
	"Rovinjska", 
	"Roda", 
	"Rodopska", 
	"Rodoljuba Čolakovića", 
	"Rožajska", 
	"Rozalin Frenklin", 
	"Roze Luksemburg", 
	"Romana Sondermajera", 
	"Romanijska", 
	"Romena Rolana", 
	"Romska", 
	"Romskih žrtava", 
	"Rose Šebez", 
	"Rospi ćuprija", 
	"Rtanjska", 
	"Rubensova", 
	"Ruvarčeva", 
	"Rudi Čajaveca", 
	"Rudnička", 
	"Rudo", 
	"Ruža", 
	"Ruže Jovanović", 
	"Ružino drvo", 
	"Ružice Miljković", 
	"Ružice Radovanović", 
	"Ružice Sokić", 
	"Ružićeva", 
	"Ruzveltova", 
	"Rumska", 
	"Rusijanova", 
	"Ruska", 
	"Rustema Sejdića", 
	"Rucovićeva", 
	"Ruđera Boškovića", 
	"Rujanska", 
	"Rujica", 
	"Rjepinova", 
	"Sava Burića", 
	"Sava avenija", 
	"Save Jovanovića", 
	"Save Jovšića", 
	"Save Vukovića", 
	"Save Grkinića", 
	"Save Kovačevića", 
	"Save Kovačevića ulica 1.", 
	"Save Kovačevića ulica 2.", 
	"Save Kovačevića ulica 3.", 
	"Save Maškovića", 
	"Save Mihića", 
	"Save Mrmka", 
	"Save Petkovića", 
	"Save Radovanovića", 
	"Save Tekelije", 
	"Save Hilandarca", 
	"Save Šumanovića", 
	"Savinjska", 
	"Savska", 
	"Savska magistrala", 
	"Savska promenada", 
	"Savski kej", 
	"Savski nasip", 
	"Savski trg", 
	"Savskih alasa", 
	"Savsko šetalište", 
	"Sadika Ramiza", 
	"Sazonova", 
	"Salvadora Aljendea", 
	"Samaranova", 
	"Samarska", 
	"Samoška", 
	"Samjuela Beketa", 
	"Sanska", 
	"Sanstefanska", 
	"Sandžačka", 
	"Saračka", 
	"Sarajevska", 
	"Sartrova", 
	"Saše Petrovića", 
	"Saše Simeunovića", 
	"Saše Filipovića", 
	"Sajmište", 
	"Sajdžijska", 
	"Sanje Živanovića", 
	"Svemira Jovanovića", 
	"Svete Milutinovića", 
	"Svete Nedelje", 
	"Svete Simića", 
	"Svete Stankovića Francuza", 
	"Svetislava Vulovića", 
	"Svetislava Vučenovića", 
	"Svetislava Cvijanovića", 
	"Svetlane Velmar Janković", 
	"Svetlane Popović Mojsilović", 
	"Svetoandrejska", 
	"Svetog Vasilija Velikog", 
	"Svetog Ermila", 
	"Svetog Klimenta", 
	"Svetog Luke", 
	"Svetog Marka", 
	"Svetog Nauma", 
	"Svetog Nikolaja Žičkog", 
	"Svetog Nikole", 
	"Svetog Prohora Pčinjskog", 
	"Svetog Rafaila Šišatovačkog", 
	"Svetog Save", 
	"Svetog Serafima Sarovskog", 
	"Svetog Stratonika", 
	"Svetogorska", 
	"Svetozara Ćorovića", 
	"Svetozara Gligorića", 
	"Svetozara Zorića", 
	"Svetozara Ivačkovića", 
	"Svetozara Markovića", 
	"Svetozara Miletića", 
	"Svetozara Mihailovića", 
	"Svetozara Papića", 
	"Svetozara Radića", 
	"Svetozara Radojčića", 
	"Svetozara Toze Nikolića", 
	"Svetolika Lazarevića Laze", 
	"Svetolika Nikačevića", 
	"Svetolika Rankovića", 
	"Svetomira Đukića", 
	"Svetomira Belića", 
	"Svetomira Nikolajevića", 
	"Svetosavska", 
	"Svetotrojčina", 
	"Svilajska", 
	"Svrljiška", 
	"Sebeš ovčanski", 
	"Sevastokratora Branka", 
	"Sevastokratora Vlatka", 
	"Sevastokratora Dejana", 
	"Severni bulevar", 
	"Sedam zemunskih planinara", 
	"Sedam stražara", 
	"Sedamnaestog oktobra", 
	"Sedme srpske brigade", 
	"Sedmog jula", 
	"Sekiljevačka", 
	"Selene Dukić", 
	"Selimira Jeftića", 
	"Semberijska", 
	"Senski trg", 
	"Sentandrejska", 
	"Servantesova", 
	"Sergeja Jesenjina", 
	"Sergija Nikolića", 
	"Serdar Jola", 
	"Serdara Janka Vukotića", 
	"Serdara Jovana Mićića", 
	"Sestara Janković", 
	"Sestara Bukumirović", 
	"Sestara Vuković", 
	"Sestara Milovanović", 
	"Sestara Strain", 
	"Senjanin Tadije", 
	"Senjanina Ive", 
	"Senjačka", 
	"Senjska", 
	"Sibinjanin Janka", 
	"Sibnička", 
	"Sibnička Nova 4", 
	"Sibnička nova 1", 
	"Sibnička nova 2", 
	"Sibnička nova 3", 
	"Sibnička nova 3 prolaz 1", 
	"Siva stena", 
	"Silvija Kranjčevića", 
	"Sime Ćirkovića", 
	"Sime Andrejevića", 
	"Sime Igumanova", 
	"Sime Lozanića", 
	"Sime Lukina Lazića", 
	"Sime Matavulja", 
	"Sime Miloševića", 
	"Sime Pandurovića", 
	"Sime Simića", 
	"Sime Trojanovića", 
	"Sime Šolaje", 
	"Simeona Končarevića", 
	"Simeona Končarevića 1. deo", 
	"Simeona Roksandića", 
	"Simina", 
	"Simićeva", 
	"Simona Bolivara", 
	"Simonidina", 
	"Singidunumska", 
	"Siniše Bognera", 
	"Siniše Vukovića", 
	"Siniše Gajina", 
	"Siniše Nikolajevića", 
	"Siniše Stankovića", 
	"Sinđelićeva", 
	"Sinđelićevo sokače", 
	"Sitnička", 
	"Sinjska", 
	"Sićevačka", 
	"Skadarlija", 
	"Skadarska", 
	"Skver Milene i Gage", 
	"Skver Mire Trailović", 
	"Skver Slobodana Markovića", 
	"Skendera Kulenovića", 
	"Skenderbegova", 
	"Skerlićeva", 
	"Skopljanska", 
	"Slaviše Vajnera", 
	"Slavka Ćuruvije", 
	"Slavka Gavrilovića", 
	"Slavka Kolara", 
	"Slavka Miljkovića", 
	"Slavka Rodića", 
	"Slavka Simića", 
	"Slavka Šlandera", 
	"Slavke Jerinić", 
	"Slavke Kaljević", 
	"Slavke Tomić", 
	"Slavonska", 
	"Slavonskih brigada", 
	"Slavoljuba Bogojevića", 
	"Slavoljuba Vuksanovića", 
	"Slavujev venac", 
	"Slanački put", 
	"Slankamenačka", 
	"Slađane Stanković", 
	"Slikarska", 
	"Slobodana Đurića", 
	"Slobodana Jankovića", 
	"Slobodana Jovanovića", 
	"Slobodana Jovića", 
	"Slobodana Jovića 2. deo", 
	"Slobodana Aligrudića", 
	"Slobodana Bajića", 
	"Slobodana Vitanovića", 
	"Slobodana Glumca", 
	"Slobodana Lale Berberskog", 
	"Slobodana Macure", 
	"Slobodana Milića", 
	"Slobodana Perića", 
	"Slobodana Perovića", 
	"Slobodana Principa", 
	"Slobodana Principa Selje", 
	"Slobodana Santrača", 
	"Slobodana Selenića", 
	"Slobodana Smiljića", 
	"Slobodanke Danke Savić", 
	"Slobode Trajković", 
	"Slovačka", 
	"Slovenska", 
	"Sloga", 
	"Službeni put", 
	"Smederevska", 
	"Smederevski put", 
	"Smetanina", 
	"Smiljanićeva", 
	"Smokvina", 
	"Smolućska", 
	"Snežane Hrepevnik", 
	"Sokače", 
	"Soko salaš", 
	"Sokobanjska", 
	"Sokolska", 
	"Solunska", 
	"Solunskih boraca", 
	"Solunskog fronta", 
	"Somborska", 
	"Sopotska", 
	"Sopoćanska", 
	"Sofije Đorđević", 
	"Sofije Dražić", 
	"Sonje Savić", 
	"Spase Garde", 
	"Spasenije Pate Marković", 
	"Spasenovićeva", 
	"Spasićev prolaz", 
	"Spasovdanska", 
	"Spasoja Hadži Popovića", 
	"Spirtina", 
	"Spomenka Gostića", 
	"Spoljna Magistralna Tangenta", 
	"Spoljna magistralna tangenta", 
	"Srbička", 
	"Srbobranska", 
	"Srboljuba Milina", 
	"Srdanov sokak", 
	"Srebrnička", 
	"Srebrnog jezera", 
	"Sredačka", 
	"Srednja", 
	"Sremska", 
	"Sremskih boraca", 
	"Sremskih odreda", 
	"Sremskog fronta", 
	"Sremskokarlovačka", 
	"Sretena Vukosavljevića", 
	"Sretena Vukosavljevića - Avalska", 
	"Sretena Kostića", 
	"Sretena Mladenovića Mike", 
	"Sretena Popovića", 
	"Sretena Stojanovića", 
	"Srećka Nedeljkovića", 
	"Srzentićeva", 
	"Srnetička", 
	"Srpska", 
	"Srpske slave", 
	"Srpskih vitezova", 
	"Srpskih serdara", 
	"Srpskih udarnih brigada", 
	"Srđana Aleksića", 
	"Srđana Kneževića", 
	"Srđana Milića", 
	"Staza Srbije", 
	"Staza Umetnost", 
	"Staza vode", 
	"Staza do Dunava", 
	"Staza pokreta", 
	"Staza prirode", 
	"Stane Milanović", 
	"Stanimira Stojanovića", 
	"Stanislava Biničkog", 
	"Stanislava Vinavera", 
	"Stanislava Sremčevića", 
	"Stanislave Pešić", 
	"Stanislavskog", 
	"Staniše Košića", 
	"Stanka Opsenice", 
	"Stanka Paunovića Veljka", 
	"Stanka Tišme", 
	"Stanka Tišme 1. deo", 
	"Stanka Tišme 2. deo", 
	"Stanka Tišme 3. deo", 
	"Stanka Tišme 4. deo", 
	"Stanka Tišme 5. deo", 
	"Stanka Tišme 6. deo", 
	"Stanka Tišme 7. deo", 
	"Stanka Tišme 8. deo", 
	"Stanka Tišme 9. deo", 
	"Stanoja Glavaša", 
	"Stanoja Milutinovića", 
	"Stanoja Simića", 
	"Stanoja Stanojevića", 
	"Stanojla Petrovića", 
	"Stara", 
	"Stare Porte", 
	"Stari Soko salaš", 
	"Stari bunar", 
	"Stari vinogradi", 
	"Stari savski most", 
	"Starine Novaka", 
	"Starih ratnika", 
	"Staro Selo", 
	"Staro naselje", 
	"Staromajdanska", 
	"Staroplaninska", 
	"Starca Vujadina", 
	"Starca Milije", 
	"Staška Sondermajera", 
	"Stevana Đurđevića Trošarinca", 
	"Stevana Jakovljevića", 
	"Stevana Aleksića", 
	"Stevana Belića", 
	"Stevana Bodnarova", 
	"Stevana Brakusa", 
	"Stevana V. Popovića", 
	"Stevana Gardinovačkog", 
	"Stevana Georgijevića", 
	"Stevana Dimitrijevića", 
	"Stevana Dubajića", 
	"Stevana Dukića", 
	"Stevana Kalembera", 
	"Stevana Karamate", 
	"Stevana Lilića", 
	"Stevana Luburića", 
	"Stevana Lukovića", 
	"Stevana Markovića", 
	"Stevana Mokranjca", 
	"Stevana Musića", 
	"Stevana Opačića", 
	"Stevana Simića", 
	"Stevana Sinđelića", 
	"Stevana Smederevca", 
	"Stevana Sremca", 
	"Stevana Tomića", 
	"Stevana Filipovića", 
	"Stevana Filipovića 2. deo", 
	"Stevana Hristića", 
	"Steve Vargaša", 
	"Steve Žigona", 
	"Steve Stankovića", 
	"Steve Todorovića", 
	"Stevčina", 
	"Stepenice", 
	"Stepenička", 
	"Stepenište Miodraga A. Dabižića", 
	"Stepojevačka", 
	"Sterijina", 
	"Stefana Dragutina Nemanjića", 
	"Stefana Musića", 
	"Stefana Prvovenčanog", 
	"Stefana Radoslava", 
	"Stiška", 
	"Stolarska", 
	"Stolačka", 
	"Stopićeva", 
	"Stojadina Mirkovića", 
	"Stojana Ljubića", 
	"Stojana Ćelića", 
	"Stojana Aralice", 
	"Stojana Aranđelovića", 
	"Stojana Boškovića", 
	"Stojana Dečermića", 
	"Stojana Markovića", 
	"Stojana Matića", 
	"Stojana Novakovića", 
	"Stojana Pačova", 
	"Stojana Protića", 
	"Stojana Stoleta Aranđelovića", 
	"Stojana Čupića", 
	"Stražarska kosa", 
	"Straževička", 
	"Stražilovska", 
	"Strahinje Petrovića", 
	"Strahinjića Bana", 
	"Straška Pindžura", 
	"Strma", 
	"Strugarska", 
	"Strumička", 
	"Stublinska", 
	"Studenac", 
	"Studenička", 
	"Studentska", 
	"Studentski trg", 
	"Stjepana Ljubiše", 
	"Stjepana Supanca", 
	"Stjepana Filipovića", 
	"Subotička", 
	"Suvoborska", 
	"Suvoplaninska", 
	"Suvopoljska", 
	"Sundečićeva", 
	"Suncokreta", 
	"Sunčani breg", 
	"Sunčevog kamena", 
	"Surdulička", 
	"Surčin na Savi", 
	"Surčinska", 
	"Surčinski put", 
	"Susedgradska", 
	"Sutjeska blok", 
	"Sutjeska ulica 1.", 
	"Sutjeska ulica 2.", 
	"Sutjeska ulica 3.", 
	"Sutjeska ulica 4.", 
	"Sutjeska ulica 5.", 
	"Sutjeska ulica 6.", 
	"Sutjeska ulica 7.", 
	"Sutjeska ulica 8.", 
	"Sjenička", 
	"Sljezove boje", 
	"Tabanovačka", 
	"Tavčareva", 
	"Tagoreova", 
	"Tadeuša Košćuška", 
	"Tadije Sondermajera", 
	"Takovska", 
	"Tamare Miletić", 
	"Tamiška", 
	"Tamnavska", 
	"Tanaska Rajića", 
	"Tankosićeva", 
	"Taraiška", 
	"Tarska", 
	"Tatar Bogdanova", 
	"Taška Načića", 
	"Tašmajdanska", 
	"Tvrtka Velikog", 
	"Tekeriška", 
	"Telečka", 
	"Temerinska", 
	"Temerinska 1. deo", 
	"Temerinska 2. deo", 
	"Temerinska 3. deo", 
	"Temerinska 4. deo", 
	"Temerinska 5. deo", 
	"Temerinska 6. deo", 
	"Temišvarska", 
	"Teodora Drajzera", 
	"Teodora Mirijevskog", 
	"Teodora Hercla", 
	"Teodora Češljara", 
	"Teodorina", 
	"Teodosija Hilandarca", 
	"Teodosijeva", 
	"Terazije", 
	"Terazijski tunel", 
	"Terzija", 
	"Tesna", 
	"Tetovska", 
	"Tibor Cerne", 
	"Tibora Sekelja", 
	"Tikveška", 
	"Timoti Džona Bajforda", 
	"Timočka", 
	"Timočke bune", 
	"Timočke divizije", 
	"Tina Ujevića", 
	"Tipografska", 
	"Tiršova", 
	"Titelska", 
	"Titova", 
	"Tihomira Višnjevca", 
	"Tihomilja Nikolića", 
	"Ticijanova", 
	"Tiška", 
	"Tkačka", 
	"Todora Dukina", 
	"Todora Manojlovića", 
	"Todora Marinkovića Solunca", 
	"Todora Pavlovića", 
	"Todora od Stalaća", 
	"Tokarska", 
	"Tolminska", 
	"Tolstojeva", 
	"Tomazeova", 
	"Tomanije Obrenović", 
	"Tomasa Mana", 
	"Tomaša Ježa", 
	"Tomaševačka", 
	"Tome Jovanovića", 
	"Tome Buše", 
	"Tome Zdravkovića", 
	"Tome Maksimovića", 
	"Tome Maretića", 
	"Tome Rosandića", 
	"Tomice Popovića", 
	"Topalovićeva", 
	"Toplice Milana", 
	"Topličin venac", 
	"Topličina", 
	"Toplička", 
	"Topola", 
	"Topolska", 
	"Topčiderska", 
	"Topčiderska dolina", 
	"Topčiderska zvezda", 
	"Topčiderski venac", 
	"Topčiderski tunel", 
	"Torlačka", 
	"Torlački vis", 
	"Toše Jovanovića", 
	"Tošin bunar", 
	"Trajanova", 
	"Trajka Grkovića", 
	"Trajka Rajkovića", 
	"Trajka Stamenkovića", 
	"Trg Branka Radičevića", 
	"Trg Nikole Pašića", 
	"Trg Politika", 
	"Trg Slavija", 
	"Trg oslobođenja", 
	"Trg republike", 
	"Trgovačka", 
	"Trgovačka ulica", 
	"Trebevićka", 
	"Trebinjska", 
	"Trepčanska", 
	"Trešnja", 
	"Trešnjinog cveta", 
	"Trećeg diviziona PVO", 
	"Trećeg januara", 
	"Trećepozivačka", 
	"Tržička", 
	"Tribalska", 
	"Trive Vitasovića", 
	"Triglavska", 
	"Trim staza", 
	"Trim staza zdravlja", 
	"Trinaestog oktobra", 
	"Triše Kaclerovića", 
	"Trnavska", 
	"Trnska", 
	"Trnski prolaz", 
	"Trogirska", 
	"Trogirska padina", 
	"Tronoška", 
	"Trstenjakova", 
	"Trubareva", 
	"Trudbenička", 
	"Tršćanska", 
	"Tuzlanska", 
	"Tuluz Lotreka", 
	"Tunelska", 
	"Tuniska", 
	"Turgenjevljeva", 
	"Tutinska", 
	"Tjentište", 
	"Ubska", 
	"Ugrinovačka", 
	"Ugrinovački put", 
	"Ugrinovački put 10. deo", 
	"Ugrinovački put 11. deo", 
	"Ugrinovački put 12. deo", 
	"Ugrinovački put 13. deo", 
	"Ugrinovački put 14. deo", 
	"Ugrinovački put 15. deo", 
	"Ugrinovački put 16. deo", 
	"Ugrinovački put 17. deo", 
	"Ugrinovački put 18. deo", 
	"Ugrinovački put 19. deo", 
	"Ugrinovački put 2. deo", 
	"Ugrinovački put 20. deo", 
	"Ugrinovački put 21. deo", 
	"Ugrinovački put 22. deo", 
	"Ugrinovački put 23. deo", 
	"Ugrinovački put 24. deo", 
	"Ugrinovački put 25. deo", 
	"Ugrinovački put 26. deo", 
	"Ugrinovački put 27. deo", 
	"Ugrinovački put 29. deo", 
	"Ugrinovački put 3. deo", 
	"Ugrinovački put 30. deo", 
	"Ugrinovački put 31. deo", 
	"Ugrinovački put 32. deo", 
	"Ugrinovački put 33. deo", 
	"Ugrinovački put 34. deo", 
	"Ugrinovački put 35. deo", 
	"Ugrinovački put 36. deo", 
	"Ugrinovački put 37. deo", 
	"Ugrinovački put 38. deo", 
	"Ugrinovački put 39. deo", 
	"Ugrinovački put 4. deo", 
	"Ugrinovački put 40. deo", 
	"Ugrinovački put 41. deo", 
	"Ugrinovački put 42. deo", 
	"Ugrinovački put 43. deo", 
	"Ugrinovački put 5. deo", 
	"Ugrinovački put 6. deo", 
	"Ugrinovački put 7. deo", 
	"Ugrinovački put 8. deo", 
	"Ugrinovački put 9. deo", 
	"Uglješe Bogunovića", 
	"Udarnih brigada", 
	"Udbinska", 
	"Užička", 
	"Uzdinska", 
	"Uzun Mirkova", 
	"Ulica 21. Kneževac", 
	"Ulica ideja", 
	"Ulofa Palmea", 
	"Ulcinjska", 
	"Umetnička", 
	"Umetnička 1. prilaz", 
	"Umčarska", 
	"Univerzijade", 
	"Unska", 
	"Uralska", 
	"Uralska - Patrisa Lumumbe", 
	"Urvinska", 
	"Uroša Kneževića", 
	"Uroša Marovića", 
	"Uroša Martinovića", 
	"Uroša Predića", 
	"Uroša Trojanovića", 
	"Uroševačka", 
	"Usek Kijevo", 
	"Uskočka", 
	"Uskočko sokače", 
	"Usnije Redžepove", 
	"Ustanička", 
	"Učenička", 
	"Učitelja Vlade Ilića", 
	"Učitelja Dragutina Prokića", 
	"Učitelja Miloša Jankovića", 
	"Učitelja Mihailovića", 
	"Učitelja Stojana Čole", 
	"Učiteljice Leontine Kraus", 
	"Učiteljice Milice Janković", 
	"Učiteljska", 
	"Ušće", 
	"Fabrisova", 
	"Fabrički put", 
	"Farmaceutska", 
	"Federika Felinija", 
	"Feliksa Kanica", 
	"Fenečka", 
	"Figarova", 
	"Filipa Višnjića", 
	"Filipa Kljajića", 
	"Filipa Hristića", 
	"Finžgarova", 
	"Flore Sends", 
	"Florina", 
	"Fotine Pejović", 
	"Fočanska", 
	"Franca Jankea", 
	"Franca Bevka", 
	"Franca Kafke", 
	"Francuska", 
	"Franje Jenča", 
	"Franje Kluza", 
	"Franje Krča", 
	"Franje Mihalića", 
	"Frederika Šopena", 
	"Frontovska", 
	"Fruškogorska", 
	"Fjodora Fjodoroviča Šljuge", 
	"Hablova", 
	"Hazarska", 
	"Hanibala Lucića", 
	"Harisa Brkića", 
	"Hasana Kikića", 
	"Hasanaginice", 
	"Hajduk Veljkov venac", 
	"Hajduk Veljkova", 
	"Hajduk Veljkovo sokače", 
	"Hajduk Stankova", 
	"Hajduk Stojka", 
	"Hajima Daviča", 
	"Hadži Nikole Živkovića", 
	"Hadži Ruvimova", 
	"Hadži-Đerina", 
	"Hadži-Melentijeva", 
	"Hadži-Mustafina", 
	"Hadži-Prodanova", 
	"Hektorovićeva", 
	"Hemingvejeva", 
	"Heroja Jajinaca", 
	"Heroja Gorana Ostojića", 
	"Heroja Milana Tepića", 
	"Heroja Nebojše Živančevića", 
	"Heroja odbrane Beograda", 
	"Hercega Stjepana", 
	"Hercegnovska", 
	"Hercegovačka", 
	"Hilandarska", 
	"Hiljadu trista kaplara", 
	"Hoze Martia", 
	"Homoljska", 
	"Hrasta lužnjaka", 
	"Hrizantema", 
	"Hrizostoma Vojinovića", 
	"Hristine Dobrović", 
	"Hristifora Žefarovića", 
	"Huana Antonia Samarana", 
	"Humska", 
	"Humski put", 
	"Husinskih rudara", 
	"Husova", 
	"Cavtatska", 
	"Camblakova", 
	"Cankareva", 
	"Cara Jovana Crnog", 
	"Cara Justinijana prvog", 
	"Cara Dušana", 
	"Cara Iraklija", 
	"Cara Konstantina", 
	"Cara Lazara", 
	"Cara Nikolaja II", 
	"Cara Radovana", 
	"Cara Romanova", 
	"Cara Uroša", 
	"Carigradska", 
	"Carice Jelene", 
	"Carice Milice", 
	"Cvetanova ćuprija", 
	"Cvetna", 
	"Cvećarska", 
	"Cvijete Zuzorić", 
	"Cvijićeva", 
	"Cerova", 
	"Cerska", 
	"Cerski venac", 
	"Cerski prolaz", 
	"Cetinjska", 
	"Celjska", 
	"Cige Milenkovića", 
	"Cincar Jankova", 
	"Cice Kalušević", 
	"Cocina", 
	"Crvena Zvezda", 
	"Crvena zvezda", 
	"Crvenih dudova", 
	"Crvenih hrastova", 
	"Crvenih javorova", 
	"Crveno barjače", 
	"Crepajska", 
	"Crikvenička", 
	"Crkvište", 
	"Crnoborska", 
	"Crnog bora", 
	"Crnog duda", 
	"Crnogorska", 
	"Crnomorska", 
	"Crnotravska", 
	"Crnojevića", 
	"Čavketov pasaž", 
	"Čazmanska", 
	"Čakorska", 
	"Čamurlijska", 
	"Čamdžijina", 
	"Čardaklijina", 
	"Čarlija Čaplina", 
	"Čarobne frule", 
	"Časlava Veljića", 
	"Čačanska", 
	"Čajetinska", 
	"Čajnička", 
	"Čegarska", 
	"Čede Zlatanovića", 
	"Čede Minderovića", 
	"Čede Mijatovića", 
	"Čedomira Krstića", 
	"Čedomira Mirkovića", 
	"Čedomira Popova", 
	"Čedomira Simića", 
	"Čedomilja M. Todorovića", 
	"Čedomilja Mitrovića", 
	"Čelebićka", 
	"Čelopečka", 
	"Čemernička", 
	"Černiševskog", 
	"Česmica", 
	"Četvrte Flavijeve legije", 
	"Četvrtog aprila", 
	"Četvrtog sremskog bataljona", 
	"Četinarska", 
	"Četrnaestog oktobra", 
	"Češka", 
	"Čika Ljubina", 
	"Čika Miše Đurića", 
	"Čingrijina", 
	"Čiča Ilijina", 
	"Čiče Romanijskog", 
	"Čičina", 
	"Čkaljino sokače", 
	"Čolak Antina", 
	"Čubrina", 
	"Čuburska", 
	"Čuvarnica kanala", 
	"Čukarička", 
	"Čumićeva", 
	"Čunarska", 
	"Čučuk Stanina", 
	"Šabana Bajramovića", 
	"Šabačka", 
	"Šavnička", 
	"Šavnička-Jablanička", 
	"Šainovac", 
	"Šamačka", 
	"Šangajska", 
	"Šangajska 1. deo", 
	"Šangajska 10. deo", 
	"Šangajska 11. deo", 
	"Šangajska 12. deo", 
	"Šangajska 2. deo", 
	"Šangajska 3. deo", 
	"Šangajska 4. deo", 
	"Šangajska 5. deo", 
	"Šangajska 6. deo", 
	"Šangajska 7. deo", 
	"Šangajska 8. deo", 
	"Šangajska 9. deo", 
	"Šandora Majora", 
	"Šantićeva", 
	"Šarplaninska", 
	"Šator planine", 
	"Šafarikova", 
	"Šafranova", 
	"Šajkaška", 
	"Švejkova", 
	"Švrakina", 
	"Ševarice", 
	"Ševina", 
	"Šekspirova", 
	"Šekularska", 
	"Šempeter Vrtojba", 
	"Šemsa Midovića", 
	"Šesnaestog oktobra", 
	"Šeste ličke divizije", 
	"Šetalište Lazaro Kardenasa", 
	"Šeširdžijska", 
	"Šejkina", 
	"Šidska", 
	"Šilerova", 
	"Šimanovačka", 
	"Široki put", 
	"Široki put 1. deo", 
	"Široki put 2. deo", 
	"Široki put 3. deo", 
	"Široki put 4. deo", 
	"Široki put 5. deo", 
	"Školska", 
	"Školski trg", 
	"Šolina", 
	"Španska", 
	"Španskih boraca", 
	"Štipska", 
	"Šturmova", 
	"Šumadijska", 
	"Šumadijske divizije", 
	"Šumadijski trg", 
	"Šumarice", 
	"Šumatovačka", 
	"Šumska", 
	"Šupljikčeva", 
	"Ščerbinova", 
	"bela staza", 
	"nekadašnja pruga uskog koloseka Beograd–Obrenovac", 
	"sokače Blaže Mašanovića", 
	"crvena staza"
]

app = Flask(__name__)

@app.route('/match_street', methods=['POST'])
def match_street():
    data = request.get_json()
    street_name = data.get('street_name')
    if not street_name:
        return jsonify({'error': 'Street name not provided'}), 400

    best_match, score = process.extractOne(street_name, street_names)
    response = {
        'input': street_name,
        'best_match': best_match,
        'score': score
    }

    response_json = json.dumps(response, ensure_ascii=False)
    return app.response_class(
        response=response_json,
        status=200,
        mimetype='application/json; charset=utf-8'
    )

if __name__ == '__main__':
    app.run(debug=True)
